### ISSUE TITLE
support java.sql.Types.INTEGER 

### ISSUE THREAD

**Issue by ssky1** [housepower/ClickHouse-Native-JDBC#122]
### JDBC version in pom.xml

ClickHouse server version 20.3.4

### ClickHouse version

2.1-stable

### Error  logs

java.lang.NullPointerException
        at com.github.housepower.jdbc.data.type.DataTypeInt8.serializeBinary(DataTypeInt8.java:50)
        at com.github.housepower.jdbc.data.Column.write(Column.java:58)
        at com.github.housepower.jdbc.data.Block.appendRow(Block.java:50)
        at com.github.housepower.jdbc.statement.ClickHousePreparedInsertStatement.addParameters(ClickHousePreparedInsertStatement.java:73)
        at com.github.housepower.jdbc.statement.ClickHousePreparedInsertStatement.addBatch(ClickHousePreparedInsertStatement.java:62)

### Steps to reproduce

A simple job  talend with jdbc driver  which read a sql table with 237 columns and insert them into 
a clickhouse table 
the type mapping are the following 
java.sql.Types.VARCHAR  ==>  String  (236 columns) 
java.sql.Types.INTEGER ==> Int8 ( 1 column) 

when a run the job,  i got the error above, but when I remove the Integer column, I don't have the error any more 

It seems the java.sql.Types.INTEGER is not supported in insert batch !

Thanks for the help

**Comment by sundy-li** [comment]
> It seems the java.sql.Types.INTEGER is not supported in insert batch !

Actually It supports all Number types. I guess your data may be a NULL Object.

**Comment by sundy-li** [comment]
Closing this issue, feel free to re-open a closed issue if needed
