### ISSUE TITLE
Connecting from a remote server

### ISSUE THREAD

**Issue by jsavaglio** [housepower/ClickHouse-Native-JDBC#129]
### JDBC version in pom.xml
2.2

### ClickHouse version
20.5.2.7

### Error  logs
Error loading JDBC Clickhouse Driver
java.sql.SQLException: Connection timed out: connect
1
	at com.github.housepower.repackaged.comgithub.housepower.jdbc.connect.PhysicalConnection.openPhysicalConnection(PhysicalConnection.java:142)
	at com.github.housepower.repackaged.comgithub.housepower.jdbc.ClickHouseConnection.createPhysicalInfo(ClickHouseConnection.java:178)
	at com.github.housepower.repackaged.comgithub.housepower.jdbc.ClickHouseConnection.createClickHouseConnection(ClickHouseConnection.java:174)
	at com.github.housepower.repackaged.comgithub.housepower.jdbc.NonRegisterDriver.connect(NonRegisterDriver.java:26)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:251)
	at feed_handler.Feed_handler.main(Feed_handler.java:211)
Caused by: java.net.ConnectException: Connection timed out: connect
	at java.base/java.net.PlainSocketImpl.connect0(Native Method)
	at java.base/java.net.PlainSocketImpl.socketConnect(PlainSocketImpl.java:101)
	at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:399)
	at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:242)
	at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:224)
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:403)
	at java.base/java.net.Socket.connect(Socket.java:591)
	at com.github.housepower.repackaged.comgithub.housepower.jdbc.connect.PhysicalConnection.openPhysicalConnection(PhysicalConnection.java:138)

### Steps to reproduce
I cannot seem to connect to Clickhouse from another server in my java project. This is the code I am using:
String clickhouseServer = "*********";
Class.forName("com.github.housepower.repackaged.comgithub.housepower.jdbc.ClickHouseDriver");
String clickhouseUrl = "jdbc:clickhouse://" + clickhouseServer + ":9000";
Connection clickhouseConn = DriverManager.getConnection(clickhouseUrl);

I have tried three different packages with no luck. I am also using DBeaver to query from the remote server but that works perfectly fine, so it is possible. Perhaps the config file needs to be changed but I am unsure what needs to be done. 
Any help would be greatly appreciated.

**Comment by sundy-li** [comment]
could you try `telnet clickhouseServer  9000`  ?

**Comment by jsavaglio** [comment]
I get: Connecting To CDRDC1-DEV01...Could not open connection to the host, on port 9000: Connect failed

Same thing on port 8123 but I can see the connections made through dbeaver go through on those ports.

**Comment by sundy-li** [comment]
It's the problem of your clickhouse-server, maybe you should check the TCP port configuration and make sure `clickhouse-client` can work with, such as
`clickhouse-client --host  ${clickhouseServer} --port 9000  `

**Comment by jsavaglio** [comment]
I can connect with the clickhouse-client:

$ clickhouse-client --host {clickhouseServer} --port 9000
>ClickHouse client version 20.5.2.7 (official build).
>Connecting to {clickhouseServer}:9000 as user default.
>Connected to ClickHouse server version 20.5.2 revision 54435.

What steps do I need to take to fix the clickhouse-server (configuration, etc.) to allow connection from remote programs?

**Comment by sundy-li** [comment]
Maybe it's related to `listen_host` configuration, it's not jdbc problem,

Closing this issue, feel free to re-open a closed issue if needed
