### ISSUE TITLE
java.lang.NullPointerException in JDBCSampler.java when used with JMeter

### ISSUE THREAD

**Issue by nikk0** [housepower/ClickHouse-Native-JDBC#139]
Hello

When i try to bench the native driver in JMeter 5.3 , i got a NPE (see below). Seems to be related to some missing features of the driver regarding the meta information of the DB objects.

### JDBC version in pom.xml
2,2-stable 

### ClickHouse version
20.5.4

### Error  logs
Jmeter log file :

```
2020-08-06 17:45:37,857 ERROR o.a.j.t.JMeterThread: Error while processing sampler: 'JDBC Request'.
java.lang.NullPointerException: null
	at org.apache.jmeter.protocol.jdbc.sampler.JDBCSampler.sample(JDBCSampler.java:90) ~[ApacheJMeter_jdbc.jar:5.3]
	at org.apache.jmeter.threads.JMeterThread.doSampling(JMeterThread.java:630) ~[ApacheJMeter_core.jar:5.3]
	at org.apache.jmeter.threads.JMeterThread.executeSamplePackage(JMeterThread.java:558) ~[ApacheJMeter_core.jar:5.3]
	at org.apache.jmeter.threads.JMeterThread.processSampler(JMeterThread.java:489) [ApacheJMeter_core.jar:5.3]
	at org.apache.jmeter.threads.JMeterThread.run(JMeterThread.java:256) [ApacheJMeter_core.jar:5.3]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_251]
2020-08-06 17:45:37,857 INFO o.a.j.t.JMeterThread: Thread is done: Thread Group 1-1
2020-08-06 17:45:37,857 INFO o.a.j.t.JMeterThread: Thread finished: Thread Group 1-1
2020-08-06 17:45:37,857 INFO o.a.j.e.StandardJMeterEngine: Notifying test listeners of end of test
2020-08-06 17:45:37,858 INFO o.a.j.g.u.JMeterMenuBar: setRunning(false, *local*)
```

### Steps to reproduce
Just configure a simple test plan with JMeter 5.3 ::

![image](https://user-images.githubusercontent.com/8555147/89553651-16177800-d80e-11ea-94ea-2ba7b9a8a12a.png)

![image](https://user-images.githubusercontent.com/8555147/89553921-73abc480-d80e-11ea-94f2-c113327dad6d.png)

### Other descriptions

Note : official ClickHouse driver does not fail

**Comment by sundy-li** [comment]
```
 catch (SQLException ex) {
            final String errCode = Integer.toString(ex.getErrorCode());
            res.setResponseMessage(ex.toString());
            res.setResponseCode(ex.getSQLState()+ " " +errCode);
            res.setResponseData(ex.getMessage().getBytes());
            res.setSuccessful(false);
        }
```

Jmeter calls `ex.getMessage()`, but the message is null.
Jmeter calls `setQueryTimeout`, but this method is not implemented in this jdbc driver, so it throws `SQLFeatureNotSupportedException`, I will create a pr to fix it.
