### ISSUE TITLE
HikariCp Accept the id of response that is not recognized by Server.

### ISSUE THREAD

**Issue by imperio-wxm** [housepower/ClickHouse-Native-JDBC#143]
### JDBC version in pom.xml
```xml
<dependency>
            <groupId>com.github.housepower</groupId>
            <artifactId>clickhouse-native-jdbc</artifactId>
            <version>2.2-stable</version>
</dependency>
```

### ClickHouse version
ClickHouse server version 20.7.2

### Error  logs
```java
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'dataSource' defined in class path resource [com/bilibili/warship/common/model/config/ClickHouseConfig.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [javax.sql.DataSource]: Factory method 'dataSource' threw exception; nested exception is com.zaxxer.hikari.pool.HikariPool$PoolInitializationException: Failed to initialize pool: Accept the id of response that is not recognized by Server.
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:655)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:483)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1336)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1176)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:556)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:516)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:324)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:226)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:322)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:276)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1307)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1227)
	at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:884)
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:788)
	... 20 common frames omitted
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [javax.sql.DataSource]: Factory method 'dataSource' threw exception; nested exception is com.zaxxer.hikari.pool.HikariPool$PoolInitializationException: Failed to initialize pool: Accept the id of response that is not recognized by Server.
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:185)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:650)
	... 34 common frames omitted
Caused by: com.zaxxer.hikari.pool.HikariPool$PoolInitializationException: Failed to initialize pool: Accept the id of response that is not recognized by Server.
	at com.zaxxer.hikari.pool.HikariPool.throwPoolInitializationException(HikariPool.java:595)
	at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:581)
	at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:115)
	at com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:81)
	at com.bilibili.warship.common.model.config.ClickHouseConfig.dataSource(ClickHouseConfig.java:40)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154)
	... 35 common frames omitted
Caused by: java.lang.IllegalStateException: Accept the id of response that is not recognized by Server.
	at com.github.housepower.jdbc.protocol.RequestOrResponse.readFrom(RequestOrResponse.java:52)
	at com.github.housepower.jdbc.connect.PhysicalConnection.receiveResponse(PhysicalConnection.java:95)
	at com.github.housepower.jdbc.connect.PhysicalConnection.receiveHello(PhysicalConnection.java:81)
	at com.github.housepower.jdbc.ClickHouseConnection.serverInfo(ClickHouseConnection.java:200)
	at com.github.housepower.jdbc.ClickHouseConnection.createPhysicalInfo(ClickHouseConnection.java:184)
	at com.github.housepower.jdbc.ClickHouseConnection.createClickHouseConnection(ClickHouseConnection.java:179)
	at com.github.housepower.jdbc.NonRegisterDriver.connect(NonRegisterDriver.java:26)
	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138)
	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:358)
	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:206)
	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:477)
	at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:560)
	... 43 common frames omitted
```

### Steps to reproduce
```java
datasource:
    hikari:
      driver-class-name: com.github.housepower.jdbc.ClickHouseDriver
      jdbc-url: jdbc:clickhouse://192.168.1.112:9000
      username:
      password:
```

### Other descriptions
Use hikaricp connection pool to report an error.
<hikariCP.version>3.4.5</hikariCP.version>

**Comment by sundy-li** [comment]
hello， can you provide a simple reproduce java code?

**Comment by Kingleading** [comment]
Caused by: java.lang.IllegalStateException: **Accept the id of response that is not recognized by Server.**

I met the same problem today,  in my situation, there is already a service start on port 9000, I changed another port in [/etc/clickhouse-server/config.xml : <tcp_port>19000</tcp_port>] ,  and the problem sovled

**Comment by pan3793** [comment]
The jdbc driver works properly with hikariCP in my application. According to @Kingleading description, it looks like not jdbc driver issue? Could you please check it? @imperio-wxm

**Comment by pan3793** [comment]
Close issue because cannot reproduce, feel free reopen it if you have a way for me to reproduce.

**Comment by Kingleading** [comment]
It would be reproduced by setting the port of jdbc-url with an active none-clickhouse-server port,  such as an active database port, it would be caused by wrong setting, not an issue
