### ISSUE TITLE
Driver should support nullable types in arrays

### ISSUE THREAD

**Issue by Ukchuvrus** [housepower/ClickHouse-Native-JDBC#144]
### JDBC version in pom.xml
2.2

### ClickHouse version
20.4.4

### Error  logs
```
Caused by: java.sql.SQLException: DataTypeNullable serializeBinary not supported
	at com.github.housepower.jdbc.data.type.complex.DataTypeNullable.serializeBinary(DataTypeNullable.java:68)
	at com.github.housepower.jdbc.data.type.complex.DataTypeArray.serializeBinary(DataTypeArray.java:92)
	at com.github.housepower.jdbc.data.Column.write(Column.java:61)
	at com.github.housepower.jdbc.data.Block.appendRow(Block.java:50)
	at com.github.housepower.jdbc.statement.ClickHousePreparedInsertStatement.addParameters(ClickHousePreparedInsertStatement.java:73)
	at com.github.housepower.jdbc.statement.ClickHousePreparedInsertStatement.addBatch(ClickHousePreparedInsertStatement.java:62)
	at ru.raiffeisen.marketdata.stores.clickhouse.ClickHouseMessageStore.lambda$storeIncrements$5(ClickHouseMessageStore.java:227)
	... 81 more
```
### Steps to reproduce
```SQL
CREATE TABLE increment
(
    asks Nested(price Nullable(Decimal64(9)))
) ENGINE = MergeTree();
```
insert something into table

### Other descriptions

Need to be supported nullable types in arrays

**Comment by sundy-li** [comment]
It's caused by `Nested ` DataType is not supported.

**Comment by Ukchuvrus** [comment]
unfortunately this is also relevant for simple arrays too
