### ISSUE TITLE
How do You use different SQL for batch processing？

### ISSUE THREAD

**Issue by wbigdata** [housepower/ClickHouse-Native-JDBC#146]
### JDBC version in pom.xml
<dependency>
    <groupId>com.github.housepower</groupId>
    <artifactId>clickhouse-native-jdbc</artifactId>
    <version>2.1-stable</version>
</dependency>

### ClickHouse version
19.16.10
### Error  logs
java.sql.SQLFeatureNotSupportedException
	at com.github.housepower.jdbc.wrapper.SQLStatement.executeBatch(SQLStatement.java:144)
	at com.clickhouse.save.SparkToClickhouse_tt$$anonfun$main$2.apply(NginxToClickhouse.scala:239)
	at com.clickhouse.save.SparkToClickhouse_tt$$anonfun$main$2.apply(NginxToClickhouse.scala:89)
	at org.apache.spark.streaming.dstream.DStream$$anonfun$foreachRDD$1$$anonfun$apply$mcV$sp$3.apply(DStream.scala:628)
	at org.apache.spark.streaming.dstream.DStream$$anonfun$foreachRDD$1$$anonfun$apply$mcV$sp$3.apply(DStream.scala:628)
	at org.apache.spark.streaming.dstream.ForEachDStream$$anonfun$1$$anonfun$apply$mcV$sp$1.apply$mcV$sp(ForEachDStream.scala:51)
	at org.apache.spark.streaming.dstream.ForEachDStream$$anonfun$1$$anonfun$apply$mcV$sp$1.apply(ForEachDStream.scala:51)
	at org.apache.spark.streaming.dstream.ForEachDStream$$anonfun$1$$anonfun$apply$mcV$sp$1.apply(ForEachDStream.scala:51)
	at org.apache.spark.streaming.dstream.DStream.createRDDWithLocalProperties(DStream.scala:416)
	at org.apache.spark.streaming.dstream.ForEachDStream$$anonfun$1.apply$mcV$sp(ForEachDStream.scala:50)
	at org.apache.spark.streaming.dstream.ForEachDStream$$anonfun$1.apply(ForEachDStream.scala:50)
	at org.apache.spark.streaming.dstream.ForEachDStream$$anonfun$1.apply(ForEachDStream.scala:50)
	at scala.util.Try$.apply(Try.scala:192)
	at org.apache.spark.streaming.scheduler.Job.run(Job.scala:39)
	at org.apache.spark.streaming.scheduler.JobScheduler$JobHandler$$anonfun$run$1.apply$mcV$sp(JobScheduler.scala:257)
	at org.apache.spark.streaming.scheduler.JobScheduler$JobHandler$$anonfun$run$1.apply(JobScheduler.scala:257)
	at org.apache.spark.streaming.scheduler.JobScheduler$JobHandler$$anonfun$run$1.apply(JobScheduler.scala:257)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
	at org.apache.spark.streaming.scheduler.JobScheduler$JobHandler.run(JobScheduler.scala:256)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

### Steps to reproduce
 val  connection:Connection = DriverManager.getConnection(s"jdbc:clickhouse://$ip:$port/database?user=$ck_username&password=$ck_password")
        val pstmt = connection.createStatement()
stream.map(x=>{
      x.value()
    }).foreachRDD(lineRdd=>{
 lineRdd.collect().foreach(item=> {
val sql1 = "insert into table1 values("+item._1+","+  ",'" + item._2+ "'" +")"
 pstmt.addBatch(sq1)
val sq2 = "insert into table2 values("+item._1+","+  ",'" + item._2+ "',"+item._3 +")"
 pstmt.addBatch(sq2)
})
 pstmt.executeBatch()
})
})

### Other descriptions
I have a log and want to write different tables for different values in the same task. How do I do that?

**Comment by sundy-li** [comment]
You need to initialize separated `PreparedStatement ` in the task for different tables.
See https://github.com/housepower/ClickHouse-Native-JDBC/blob/master/src/main/java/examples/BatchQuery.java#L22

Such as 
```
 PreparedStatement pstmt1 = connection.prepareStatement("INSERT INTO a1 VALUES(?, ?, ?)");
 PreparedStatement pstmt2 = connection.prepareStatement("INSERT INTO a2 VALUES(?, ?, ?)");

lineRdd.collect().foreach(item=> {
   pstsm1.set()
   pstmt1.addBatch()

  pstmt2.set()
  pstmt2.addBatch()
})

```

**Comment by wbigdata** [comment]
> 您需要`PreparedStatement `在任务中为不同的表单独初始化。
> 参见https://github.com/housepower/ClickHouse-Native-JDBC/blob/master/src/main/java/examples/BatchQuery.java#L22
> 
> 如
> 
> ```
>  PreparedStatement pstmt1 = connection.prepareStatement("INSERT INTO a1 VALUES(?, ?, ?)");
>  PreparedStatement pstmt2 = connection.prepareStatement("INSERT INTO a2 VALUES(?, ?, ?)");
> 
> lineRdd.collect().foreach(item=> {
>    pstsm1.set()
>    pstmt1.addBatch()
> 
>   pstmt2.set()
>   pstmt2.addBatch()
> })
> ```
I tried it and it still didn't work，see my code thanks.
```
 val pstmt= connection.prepareStatement(s"insert into $database.$tableNameTestvalues (?,?,?,?,?,?,?,?,?,?)")
 val errpstmt = connection.prepareStatement(s"insert into $database.$tableNameError values (?,?,?,?,?,?,?,?)")


lineRdd.collect().foreach(item=> {
pstmt.setInt(1,iten._1)
pstmt.setInt(2,iten._2)
pstmt.addBatch()
if(item._3 == "-1"){
errpstmt.setInt(1,item_5)
errpstmt.setInt(2,item_6)
errpstmt.setInt(3,item_7)
errpstmt.addBatch()
}
})

//此行报错
pstmt.executeBatch()  
errpstmt.executeBatch()




ErrorLog:
com.github.housepower.jdbc.ClickHouseSQLException: DB::ExceptionDB::Exception: Not found column type in block. There are only columns: errorTime,uid, errorType.
```
The error should be the field information for the ERRpSTMT used when executing the PSTMT

**Comment by sundy-li** [comment]
If you are using `batch insert` for different tables, you need to use separated `Connection` too.

```
  Connection connection = DriverManager.getConnection("jdbc:clickhouse://127.0.0.1:9000");
        PreparedStatement pstmt = connection.prepareStatement("INSERT INTO test_jdbc_example VALUES(?, ?, ?)");
        Connection connection2 = DriverManager.getConnection("jdbc:clickhouse://127.0.0.1:9000");
        PreparedStatement pstmt2 = connection.prepareStatement("INSERT INTO test_jdbc_example2 VALUES(?, ?)");

```

**Comment by wbigdata** [comment]
> If you are using `batch insert` for different tables, you need to use separated `Connection` too.
> 
> ```
>   Connection connection = DriverManager.getConnection("jdbc:clickhouse://127.0.0.1:9000");
>         PreparedStatement pstmt = connection.prepareStatement("INSERT INTO test_jdbc_example VALUES(?, ?, ?)");
>         Connection connection2 = DriverManager.getConnection("jdbc:clickhouse://127.0.0.1:9000");
>         PreparedStatement pstmt2 = connection.prepareStatement("INSERT INTO test_jdbc_example2 VALUES(?, ?)");
> ```

Yes, thank you very much. Problem solved
