### ISSUE TITLE
Can not write Array<String> using Spark

### ISSUE THREAD

**Issue by pan3793** [housepower/ClickHouse-Native-JDBC#165]
### JDBC version in pom.xml

2.3-SNAPSHOT (build on mainline code)

### ClickHouse version

20.8-lts

### Other Components Version

Spark 2.4.0-cdh6.3.1 with Scala 2.11 and Hadoop 3.0.0-cdh6.3.1

### Error  logs

```
Lost task 0.3 in stage 14.0 (TID 298, cdh-worker002, executor 4): java.lang.IllegalArgumentException: Can't get JDBC type for array<string>
	at org.apache.spark.sql.execution.datasources.jdbc.JdbcUtils$$anonfun$org$apache$spark$sql$execution$datasources$jdbc$JdbcUtils$$getJdbcType$2.apply(JdbcUtils.scala:183)
	at org.apache.spark.sql.execution.datasources.jdbc.JdbcUtils$$anonfun$org$apache$spark$sql$execution$datasources$jdbc$JdbcUtils$$getJdbcType$2.apply(JdbcUtils.scala:183)
	at scala.Option.getOrElse(Option.scala:121)
	at org.apache.spark.sql.execution.datasources.jdbc.JdbcUtils$.org$apache$spark$sql$execution$datasources$jdbc$JdbcUtils$$getJdbcType(JdbcUtils.scala:182)
	at org.apache.spark.sql.execution.datasources.jdbc.JdbcUtils$$anonfun$20.apply(JdbcUtils.scala:645)
	at org.apache.spark.sql.execution.datasources.jdbc.JdbcUtils$$anonfun$20.apply(JdbcUtils.scala:645)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
	at scala.collection.mutable.ArrayOps$ofRef.map(ArrayOps.scala:186)
	at org.apache.spark.sql.execution.datasources.jdbc.JdbcUtils$.savePartition(JdbcUtils.scala:645)
	at org.apache.spark.sql.execution.datasources.jdbc.JdbcUtils$$anonfun$saveTable$1.apply(JdbcUtils.scala:834)
	at org.apache.spark.sql.execution.datasources.jdbc.JdbcUtils$$anonfun$saveTable$1.apply(JdbcUtils.scala:834)
	at org.apache.spark.rdd.RDD$$anonfun$foreachPartition$1$$anonfun$apply$28.apply(RDD.scala:935)
	at org.apache.spark.rdd.RDD$$anonfun$foreachPartition$1$$anonfun$apply$28.apply(RDD.scala:935)
	at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:2121)
	at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:2121)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
	at org.apache.spark.scheduler.Task.run(Task.scala:121)
	at org.apache.spark.executor.Executor$TaskRunner$$anonfun$11.apply(Executor.scala:407)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1408)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:413)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```
### Steps to reproduce

Writing data using Spark to a table which has `Array<String>` columns.

### Other descriptions

This issue should be the limitation of Spark JDBC writer, and may be beyond the scope of this JDBC driver, but I think many ClickHouse-Native-JDBC user would encounter this issue.

**Comment by pan3793** [comment]
Some investigation:
- Spark provide some internal `JdbcDialect` like `MySQL`, `PostgreSQL`, and which to use is chosen by jdbc url schema.
- If no `JdbcDialect` match, fallback to use `NoopDialect`
- Implement `JdbcDialect` can overwrite methods like 
  - `def getTruncateQuery(table: String): String`
  - `def getJDBCType(dt: DataType): Option[JdbcType]`
  - ...

Maybe we can implement `ClickHouseDialect` and using `JdbcDialects.registerDialect(dialect: JdbcDialect)` to register it to support more ClickHouse feature.

**Comment by sundy-li** [comment]
If we implement `ClickHouseDialect `, we may hava spark dependencies.
I think this could be done on the client side, and we can provide some examples in Example module.

**Comment by pan3793** [comment]
After a discussion with @sundy-li offline, we'd like to introduce a new module `clickhouse-intergration-spark` to implement the **clickhouse-on-spark**. 

I have implemented a prototype support DataFrame `ArrayType(StringType)` write into a ClickHouse `Array<String>` column, and will raise a PR in fews day.

The first version will build on Spark 2.4.x&Scala 2.11. And the user API likes:
```scala
df.write
  .format("jdbc")
  .mode("overwrite")
  .option("truncate", "true")
  .option("driver", "com.github.housepower.jdbc.ClickHouseDriver")
  .option("url", "jdbc:clickhouse://127.0.0.1:9000")
  .option("user", "default")
  .option("password", "")
  .option("dbtable", "default.xm_terms")
  .option("batchsize", 10000)
  .option("isolationLevel", "NONE")
  .save
```
