### ISSUE TITLE
Client should retry but not

### ISSUE THREAD

**Issue by pan3793** [housepower/ClickHouse-Native-JDBC#182]
### JDBC version in pom.xml
2.3-stable shaded version

### ClickHouse version
20.8-lts

### Error  logs
```
20/10/29 12:13:36 ERROR yarn.Client: Application diagnostics message: User class threw exception: com.github.housepower.jdbc.ClickHouseSQLException: DB::ExceptionDB::Exception: WRITE locking attempt on "xm_100m.xm_user" has timed out! (120000ms) Possible deadlock avoided. Client should retry.. Stack trace:

0. Poco::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0x18ba03d0 in /usr/bin/clickhouse
1. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0xe606dad in /usr/bin/clickhouse
2. ? @ 0x15d1177d in /usr/bin/clickhouse
3. DB::IStorage::lockExclusively(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000l> > const&) @ 0x15d10c01 in /usr/bin/clickhouse
4. DB::InterpreterDropQuery::executeToTable(DB::StorageID const&, DB::ASTDropQuery const&) @ 0x15839c81 in /usr/bin/clickhouse
5. DB::InterpreterDropQuery::execute() @ 0x1583bb50 in /usr/bin/clickhouse
6. ? @ 0x15bd7f22 in /usr/bin/clickhouse
7. DB::executeQuery(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, DB::Context&, bool, DB::QueryProcessingStage::Enum, bool) @ 0x15bd9882 in /usr/bin/clickhouse
8. DB::TCPHandler::runImpl() @ 0x1626e975 in /usr/bin/clickhouse
9. DB::TCPHandler::run() @ 0x1626f6e0 in /usr/bin/clickhouse
10. Poco::Net::TCPServerConnection::start() @ 0x18abe23b in /usr/bin/clickhouse
11. Poco::Net::TCPServerDispatcher::run() @ 0x18abe6cb in /usr/bin/clickhouse
12. Poco::PooledThread::run() @ 0x18c3d1a6 in /usr/bin/clickhouse
13. Poco::ThreadImpl::runnableEntry(void*) @ 0x18c385a0 in /usr/bin/clickhouse
14. start_thread @ 0x7dd5 in /usr/lib64/libpthread-2.17.so
15. __clone @ 0xfe02d in /usr/lib64/libc-2.17.so

	at com.github.housepower.jdbc.protocol.ExceptionResponse.readExceptionFrom(ExceptionResponse.java:32)
	at com.github.housepower.jdbc.protocol.RequestOrResponse.readFrom(RequestOrResponse.java:38)
	at com.github.housepower.jdbc.connect.PhysicalConnection.receiveResponse(PhysicalConnection.java:95)
	at com.github.housepower.jdbc.ClickHouseConnection.lambda$sendQueryRequest$0(ClickHouseConnection.java:145)
	at com.github.housepower.jdbc.protocol.QueryResponse.consumeDataResponse(QueryResponse.java:39)
	at com.github.housepower.jdbc.protocol.QueryResponse.ensureHeaderConsumed(QueryResponse.java:32)
	at com.github.housepower.jdbc.protocol.QueryResponse.header(QueryResponse.java:25)
	at com.github.housepower.jdbc.statement.ClickHouseStatement.executeUpdate(ClickHouseStatement.java:68)
	at org.apache.spark.sql.execution.datasources.jdbc.JdbcUtils$.truncateTable(JdbcUtils.scala:113)
	at org.apache.spark.sql.execution.datasources.jdbc.JdbcRelationProvider.createRelation(JdbcRelationProvider.scala:56)
	at org.apache.spark.sql.execution.datasources.SaveIntoDataSourceCommand.run(SaveIntoDataSourceCommand.scala:45)
	at org.apache.spark.sql.execution.command.ExecutedCommandExec.sideEffectResult$lzycompute(commands.scala:70)
	at org.apache.spark.sql.execution.command.ExecutedCommandExec.sideEffectResult(commands.scala:68)
	at org.apache.spark.sql.execution.command.ExecutedCommandExec.doExecute(commands.scala:86)
	at org.apache.spark.sql.execution.SparkPlan$$anonfun$execute$1.apply(SparkPlan.scala:131)
	at org.apache.spark.sql.execution.SparkPlan$$anonfun$execute$1.apply(SparkPlan.scala:127)
	at org.apache.spark.sql.execution.SparkPlan$$anonfun$executeQuery$1.apply(SparkPlan.scala:155)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
	at org.apache.spark.sql.execution.SparkPlan.executeQuery(SparkPlan.scala:152)
	at org.apache.spark.sql.execution.SparkPlan.execute(SparkPlan.scala:127)
	at org.apache.spark.sql.execution.QueryExecution.toRdd$lzycompute(QueryExecution.scala:80)
	at org.apache.spark.sql.execution.QueryExecution.toRdd(QueryExecution.scala:80)
	at org.apache.spark.sql.DataFrameWriter$$anonfun$runCommand$1.apply(DataFrameWriter.scala:668)
	at org.apache.spark.sql.DataFrameWriter$$anonfun$runCommand$1.apply(DataFrameWriter.scala:668)
	at org.apache.spark.sql.execution.SQLExecution$$anonfun$withNewExecutionId$1.apply(SQLExecution.scala:78)
	at org.apache.spark.sql.execution.SQLExecution$.withSQLConfPropagated(SQLExecution.scala:125)
	at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:73)
	at org.apache.spark.sql.DataFrameWriter.runCommand(DataFrameWriter.scala:668)
	at org.apache.spark.sql.DataFrameWriter.saveToV1Source(DataFrameWriter.scala:276)
	at org.apache.spark.sql.DataFrameWriter.save(DataFrameWriter.scala:270)
	at com.bestcem.xenon.xm.spark.XmDataImportCkJob.save2Ck(XmDataImportCkJob.scala:65)
	at com.bestcem.xenon.xm.spark.XmDataImportCkJob.run(XmDataImportCkJob.scala:48)
	at com.bestcem.xenon.xm.spark.XmDataImportCkJob$.main(XmDataImportCkJob.scala:12)
	at com.bestcem.xenon.xm.spark.XmDataImportCkJob.main(XmDataImportCkJob.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.spark.deploy.yarn.ApplicationMaster$$anon$2.run(ApplicationMaster.scala:673)
```

**Comment by pan3793** [comment]
It's a expected behavior, should handle in user code.
