### ISSUE TITLE
Concurrent queries with a single connection report errors

### ISSUE THREAD

**Issue by nettm** [housepower/ClickHouse-Native-JDBC#227]
### Environment

- OS version: windows 10
- JDK version:1.8
- ClickHouse Server version: 20.5.2.7
- ClickHouse Native JDBC version:2.4.2
- (Optional) Spark version: N/A
- (Optional) Other components' version: N/A

### Error logs

```
java.lang.IllegalStateException: Accept the id of response that is not recognized by Server.
	at com.github.housepower.jdbc.protocol.RequestOrResponse.readFrom(RequestOrResponse.java:66)
	at com.github.housepower.jdbc.connect.PhysicalConnection.receiveResponse(PhysicalConnection.java:99)
	at com.github.housepower.jdbc.connect.PhysicalConnection.ping(PhysicalConnection.java:53)
	at com.github.housepower.jdbc.ClickHouseConnection.getHealthyPhysicalConnection(ClickHouseConnection.java:161)
	at com.github.housepower.jdbc.ClickHouseConnection.sendQueryRequest(ClickHouseConnection.java:139)
	at com.github.housepower.jdbc.statement.ClickHouseStatement.executeUpdate(ClickHouseStatement.java:83)
	at com.github.housepower.jdbc.statement.ClickHouseStatement.executeQuery(ClickHouseStatement.java:63)
	at com.hh.dw.metadata.scanner.clickhouse.scan.ClickhouseMetadataService.getTableList(ClickhouseMetadataService.java:103)
	at com.hh.dw.metadata.scanner.clickhouse.scan.ClickhouseScanService.scan(ClickhouseScanService.java:133)
	at com.hh.dw.metadata.scanner.clickhouse.scan.ClickhouseScanService.lambda$scan$0(ClickhouseScanService.java:85)
	at com.hh.dw.metadata.scanner.common.service.ParallelService.lambda$null$0(ParallelService.java:32)
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1640)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

### Steps to reproduce
A concurrent query using the same connection reports the above error

### Other descriptions
nothings

**Comment by pan3793** [comment]
JDBC is not design for async query, you can use Connection Pool to avoid concurrent query in single connection.
https://housepower.github.io/ClickHouse-Native-JDBC/guide/connection_pool.html
