### ISSUE TITLE
"ClickHouse-Native-JDBC" and "sqlite-jdbc-3.34.0" drivers conflict.

### ISSUE THREAD

**Issue by gmxyb** [housepower/ClickHouse-Native-JDBC#266]
Pseudo code：
```
Class.forName("com.github.housepower.jdbc.ClickHouseDriver");
Class.forName("org.sqlite.JDBC"); // https://github.com/xerial/sqlite-jdbc

Connection c = java.sql.DriverManager.getConnection("jdbc:sqlite:/the/path/of/file.db", "", “”);
```
ERROR:
```
com.github.housepower.jdbc.exception.InvalidValueException: java.net.URISyntaxException: jdbc:sqlite:/the/path/of/file.db: No valid host was found
        at com.github.housepower.jdbc.ClickhouseJdbcUrlParser.parseJdbcUrl(ClickhouseJdbcUrlParser.java:56)
        at com.github.housepower.jdbc.settings.ClickHouseConfig$Builder.withJdbcUrl(ClickHouseConfig.java:278)
        at com.github.housepower.jdbc.ClickHouseDriver.connect(ClickHouseDriver.java:43)
        at com.github.housepower.jdbc.ClickHouseDriver.connect(ClickHouseDriver.java:25)
        at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
        at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:228)
```

**Comment by gmxyb** [comment]
I know the reason for this bug. 

In ClickHouseDriver.java :
```
   @Override
    public ClickHouseConnection connect(String url, Properties properties) throws SQLException {
         if(!this.acceptsURL(url))  return null;      //  add this line,  prevent withJdbcUrl(url) except !
         ClickHouseConfig cfg = ClickHouseConfig.Builder.builder()
                .withJdbcUrl(url)
                .withProperties(properties)
                .build();
        return connect(url, cfg);
    }
```
