### ISSUE TITLE
How to define engine when use spark jdbc overwrite to clickhouse

### ISSUE THREAD

**Issue by sheldon1iu** [housepower/ClickHouse-Native-JDBC#296]
I can use append mode successfully but overwrite mode failed,when overwrite table is deleted but not be recreated. I guess it caused by the engine definition but I dont know how to define it.

**Comment by sundy-li** [comment]
It has `truncate` option, but If you want to override some partitions, you should send a `drop partition` query before sending the data.

**Comment by sheldon1iu** [comment]
> It has `truncate` option, but If you want to override some partitions, you should send a `drop partition` query before sending the data.

I want to use 
`    JdbcDialects.registerDialect(ClickHouseDialect)
    df.write
      .format("jdbc")
      .mode("overwrite")
      .option("driver", "com.github.housepower.jdbc.ClickHouseDriver")
      .option("url","jdbc:clickhouse://xxx:9090")
      .option("user","root")
      .option("password", "xxx")
      .option("dbtable", "xxx")
      .option("numPartitions", "1")
      .option("truncate", "true")
      .option("batchsize", 10)
      .option("isolationLevel", "NONE")
      .save` 
to delete the entire table if it exsists and then automatically create the table according to dataframe and import the data, just like spark's overwrite mode, but an error was reported when using this JDBC.
But when I created the table, I changed the overwrite mode to append mode, no error was reported, and the data was successfully written into the clickhouse table.

**Comment by sundy-li** [comment]
You can paste the error logs.

**Comment by sheldon1iu** [comment]
> You can paste the error logs.

Exception in thread "main" com.github.housepower.jdbc.ClickHouseSQLException: DB::ExceptionDB::Exception: Syntax error: failed at position 45 (end of query): . Expected one of: storage definition, ENGINE, AS. Stack trace:

0. DB::parseQueryAndMovePosition(DB::IParser&, char const*&, char const*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, bool, unsigned long, unsigned long) @ 0xe997949 in /usr/bin/clickhouse
1. ? @ 0xdef9c45 in /usr/bin/clickhouse
2. DB::executeQuery(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, DB::Context&, bool, DB::QueryProcessingStage::Enum, bool) @ 0xdef98bd in /usr/bin/clickhouse
3. DB::TCPHandler::runImpl() @ 0xe5cf926 in /usr/bin/clickhouse
4. DB::TCPHandler::run() @ 0xe5dbe27 in /usr/bin/clickhouse
5. Poco::Net::TCPServerConnection::start() @ 0x10d85cff in /usr/bin/clickhouse
6. Poco::Net::TCPServerDispatcher::run() @ 0x10d87711 in /usr/bin/clickhouse
7. Poco::PooledThread::run() @ 0x10eb4ce9 in /usr/bin/clickhouse
8. Poco::ThreadImpl::runnableEntry(void*) @ 0x10eb0c7a in /usr/bin/clickhouse
9. start_thread @ 0x9609 in /usr/lib/x86_64-linux-gnu/libpthread-2.31.so
10. __clone @ 0x122293 in /usr/lib/x86_64-linux-gnu/libc-2.31.so

	at com.github.housepower.jdbc.protocol.ExceptionResponse.readExceptionFrom(ExceptionResponse.java:36)
	at com.github.housepower.jdbc.protocol.Response.readFrom(Response.java:35)
	at com.github.housepower.jdbc.connect.NativeClient.receiveResponse(NativeClient.java:178)
	at com.github.housepower.jdbc.connect.NativeClient.lambda$receiveQuery$0(NativeClient.java:135)
	at com.github.housepower.jdbc.stream.ClickHouseQueryResult.consumeDataResponse(ClickHouseQueryResult.java:89)
	at com.github.housepower.jdbc.stream.ClickHouseQueryResult.ensureHeaderConsumed(ClickHouseQueryResult.java:82)
	at com.github.housepower.jdbc.stream.ClickHouseQueryResult.header(ClickHouseQueryResult.java:43)
	at com.github.housepower.jdbc.statement.ClickHouseStatement.executeUpdate(ClickHouseStatement.java:93)
	at org.apache.spark.sql.execution.datasources.jdbc.JdbcUtils$.createTable(JdbcUtils.scala:859)
	at org.apache.spark.sql.execution.datasources.jdbc.JdbcRelationProvider.createRelation(JdbcRelationProvider.scala:81)
	at org.apache.spark.sql.execution.datasources.SaveIntoDataSourceCommand.run(SaveIntoDataSourceCommand.scala:45)
	at org.apache.spark.sql.execution.command.ExecutedCommandExec.sideEffectResult$lzycompute(commands.scala:70)
	at org.apache.spark.sql.execution.command.ExecutedCommandExec.sideEffectResult(commands.scala:68)
	at org.apache.spark.sql.execution.command.ExecutedCommandExec.doExecute(commands.scala:86)
	at org.apache.spark.sql.execution.SparkPlan$$anonfun$execute$1.apply(SparkPlan.scala:131)
	at org.apache.spark.sql.execution.SparkPlan$$anonfun$execute$1.apply(SparkPlan.scala:127)
	at org.apache.spark.sql.execution.SparkPlan$$anonfun$executeQuery$1.apply(SparkPlan.scala:155)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
	at org.apache.spark.sql.execution.SparkPlan.executeQuery(SparkPlan.scala:152)
	at org.apache.spark.sql.execution.SparkPlan.execute(SparkPlan.scala:127)
	at org.apache.spark.sql.execution.QueryExecution.toRdd$lzycompute(QueryExecution.scala:80)
	at org.apache.spark.sql.execution.QueryExecution.toRdd(QueryExecution.scala:80)
	at org.apache.spark.sql.DataFrameWriter$$anonfun$runCommand$1.apply(DataFrameWriter.scala:668)
	at org.apache.spark.sql.DataFrameWriter$$anonfun$runCommand$1.apply(DataFrameWriter.scala:668)
	at org.apache.spark.sql.execution.SQLExecution$$anonfun$withNewExecutionId$1.apply(SQLExecution.scala:78)
	at org.apache.spark.sql.execution.SQLExecution$.withSQLConfPropagated(SQLExecution.scala:125)
	at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:73)
	at org.apache.spark.sql.DataFrameWriter.runCommand(DataFrameWriter.scala:668)
	at org.apache.spark.sql.DataFrameWriter.saveToV1Source(DataFrameWriter.scala:276)
	at org.apache.spark.sql.DataFrameWriter.save(DataFrameWriter.scala:270)
	at com.fmtt.App$.main(App.scala:51)
	at com.fmtt.App.main(App.scala)

**Comment by sundy-li** [comment]
try add
```
 .option("createTableOptions", "ENGINE=Log()")

```

**Comment by sheldon1iu** [comment]
> try add
> 
> ```
>  .option("createTableOptions", "ENGINE=Log()")
> ```

Succeed! Thank you very much, But can you tell me where to find the documentation for these option settings, and it is recommended to add this trick to your example.

**Comment by sheldon1iu** [comment]
> createTableOptions

@sundy-li 
I find it in spark's document,thanks again.

**Comment by sheldon1iu** [comment]
https://spark.apache.org/docs/3.0.1/sql-data-sources-jdbc.html
![image](https://user-images.githubusercontent.com/39169452/105448885-28994700-5cb2-11eb-83e8-be94aa2ced22.png)
