### ISSUE TITLE
insert to clickhouse by  spark sql  meet error

### ISSUE THREAD

**Issue by mullerhai** [housepower/ClickHouse-Native-JDBC#313]
### Environment

- OS version:  mac  big sur
- JDK version: 1.8 221
- ClickHouse Server version: 2.5.3
- ClickHouse Native JDBC version: 2.5.2
- (Optional) Spark version: N/A 3.0.1
- (Optional) Other components' version: N/A

 insert data by spark  use overwrite mode meet this error, but if use append mode  it can work
```
  def  exportClickHouse(df:DataFrame,ckTable:String="muller_test"):Unit={
    df.write
      .format("jdbc")
      .mode("overwrite") // append
      .option("driver", "com.github.housepower.jdbc.ClickHouseDriver")
      .option("url", "jdbc:clickhouse://221.228.107.180:9000")
      .option("user", "ck")
      .option("password", "123456qwer")
      .option("dbtable", s"${ckTable}")
//      .option("truncate", "true")
      .option("batchsize", 10000)
      .option("ENGINE","mergetree")
//      .option("isolationLevel", "NONE")
      .save
  }
```
### Error logs

```
Exception in thread "main" com.github.housepower.jdbc.ClickHouseSQLException: DB::ExceptionDB::Exception: Syntax error: failed at position 66 (end of query): . Expected one of: ENGINE, storage definition. Stack trace:

0. Poco::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0x13cd24bc in /usr/bin/clickhouse
1. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0xa4346c9 in /usr/bin/clickhouse
2. ? @ 0xa0564ae in /usr/bin/clickhouse
3. ? @ 0x10e0d954 in /usr/bin/clickhouse
4. DB::executeQuery(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, DB::Context&, bool, DB::QueryProcessingStage::Enum, bool) @ 0x10e0fa5f in /usr/bin/clickhouse
5. DB::TCPHandler::runImpl() @ 0x1123e65c in /usr/bin/clickhouse
6. DB::TCPHandler::run() @ 0x1123f299 in /usr/bin/clickhouse
7. Poco::Net::TCPServerConnection::start() @ 0x13c11197 in /usr/bin/clickhouse
8. Poco::Net::TCPServerDispatcher::run() @ 0x13c1158b in /usr/bin/clickhouse
9. Poco::PooledThread::run() @ 0x13d481ae in /usr/bin/clickhouse
10. Poco::ThreadImpl::runnableEntry(void*) @ 0x13d44ea9 in /usr/bin/clickhouse
11. start_thread @ 0x7dd5 in /usr/lib64/libpthread-2.17.so
12. __clone @ 0xfdead in /usr/lib64/libc-2.17.so

	at com.github.housepower.jdbc.protocol.ExceptionResponse.readExceptionFrom(ExceptionResponse.java:36)
	at com.github.housepower.jdbc.protocol.Response.readFrom(Response.java:35)
	at com.github.housepower.jdbc.connect.NativeClient.receiveResponse(NativeClient.java:178)
	at com.github.housepower.jdbc.connect.NativeClient.lambda$receiveQuery$0(NativeClient.java:135)
	at com.github.housepower.jdbc.stream.ClickHouseQueryResult.consumeDataResponse(ClickHouseQueryResult.java:89)
	at com.github.housepower.jdbc.stream.ClickHouseQueryResult.ensureHeaderConsumed(ClickHouseQueryResult.java:82)
	at com.github.housepower.jdbc.stream.ClickHouseQueryResult.header(ClickHouseQueryResult.java:43)
	at com.github.housepower.jdbc.statement.ClickHouseStatement.executeUpdate(ClickHouseStatement.java:93)
	at org.apache.spark.sql.execution.datasources.jdbc.JdbcUtils$.createTable(JdbcUtils.scala:881)
	at org.apache.spark.sql.execution.datasources.jdbc.JdbcRelationProvider.createRelation(JdbcRelationProvider.scala:62)
	at org.apache.spark.sql.execution.datasources.SaveIntoDataSourceCommand.run(SaveIntoDataSourceCommand.scala:46)
	at org.apache.spark.sql.execution.command.ExecutedCommandExec.sideEffectResult$lzycompute(commands.scala:70)
	at org.apache.spark.sql.execution.command.ExecutedCommandExec.sideEffectResult(commands.scala:68)
	at org.apache.spark.sql.execution.command.ExecutedCommandExec.doExecute(commands.scala:90)
	at org.apache.spark.sql.execution.SparkPlan.$anonfun$execute$1(SparkPlan.scala:175)
	at org.apache.spark.sql.execution.SparkPlan.$anonfun$executeQuery$1(SparkPlan.scala:213)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
	at org.apache.spark.sql.execution.SparkPlan.executeQuery(SparkPlan.scala:210)
	at org.apache.spark.sql.execution.SparkPlan.execute(SparkPlan.scala:171)
	at org.apache.spark.sql.execution.QueryExecution.toRdd$lzycompute(QueryExecution.scala:122)
	at org.apache.spark.sql.execution.QueryExecution.toRdd(QueryExecution.scala:121)
	at org.apache.spark.sql.DataFrameWriter.$anonfun$runCommand$1(DataFrameWriter.scala:963)
	at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$5(SQLExecution.scala:100)
	at org.apache.spark.sql.execution.SQLExecution$.withSQLConfPropagated(SQLExecution.scala:160)
	at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$1(SQLExecution.scala:87)
	at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:764)
	at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:64)
	at org.apache.spark.sql.DataFrameWriter.runCommand(DataFrameWriter.scala:963)
	at org.apache.spark.sql.DataFrameWriter.saveToV1Source(DataFrameWriter.scala:415)
	at org.apache.spark.sql.DataFrameWriter.save(DataFrameWriter.scala:399)
```

**Comment by pan3793** [comment]
The stack trace point that `Expected one of: ENGINE, storage definition.`

In demo code, we set `option("createTableOptions", "ENGINE=Log()")`
```
df.write
      .format("jdbc")
      .option("createTableOptions", "ENGINE=Log()")
      [...]
      .save
```
And the final create table DDL would be: 
```
create table xxx (
 ...
) ENGINE=Log()
```
Please follow clickhouse doc to define `createTableOptions` properly.

**Comment by mullerhai** [comment]
> The stack trace point that `Expected one of: ENGINE, storage definition.`
> 
> In demo code, we set `option("createTableOptions", "ENGINE=Log()")`
> 
> ```
> df.write
>       .format("jdbc")
>       .option("createTableOptions", "ENGINE=Log()")
>       [...]
>       .save
> ```
> 
> And the final create table DDL would be:
> 
> ```
> create table xxx (
>  ...
> ) ENGINE=Log()
> ```
> 
> Please follow clickhouse doc to define `createTableOptions` properly.

thank you ,It's  work fine now
