### ISSUE TITLE
Do we support insert values  by List<object> in java  or Seq[columnStruct] in scala

### ISSUE THREAD

**Issue by mullerhai** [housepower/ClickHouse-Native-JDBC#314]
### Environment

- OS version: mac big sur
- JDK version: 1.8 
- ClickHouse Server version:  2.5.2
- ClickHouse Native JDBC version:2.5.2
- (Optional) Spark version: N/A3.0.1
- (Optional) Other components' version: N/A

Hi , now  I wanna  insert  into clickhouse  batch list Object  data ,like   sql-object orm mapper,   insert List[Object] to ck, but now I just find  raw  query sql to insert to ck , it  is not  convenient for me , or do we support relation other jdbc  orm  framestruct , like  spring boot   ,mybatis, hibernete
### Error logs

```
paste your error logs here
```

**Comment by mullerhai** [comment]
I  use scala ,I know spark now support write data to ck, but need  convert data to dataframe, now I want to try  [SLICK ]

**Comment by pan3793** [comment]
I think `mybatis` would work fine, it just mapping Java Objects to JDBC values and dynamic assemble sql. And `mybatis` also provide extend api to define custom value converter and you can use xml to define sql template.

**Comment by mullerhai** [comment]
good news and bad news 
good news ,scala slick support clickhouse by raw sql ,
bad news  when use slick  orm mapper ,meet error
```
Exception in thread "main" java.lang.NullPointerException
	at java.util.Arrays.fill(Arrays.java:3129)
	at com.github.housepower.jdbc.statement.AbstractPreparedStatement.clearParameters(AbstractPreparedStatement.java:168)
	at slick.jdbc.LoggingPreparedStatement.clearParameters(LoggingStatement.scala:184)
	at slick.jdbc.JdbcActionComponent$InsertActionComposerImpl$MultiInsertAction.$anonfun$run$17(JdbcActionComponent.scala:531)
	at slick.jdbc.JdbcBackend$SessionDef.withPreparedStatement(JdbcBackend.scala:425)
	at slick.jdbc.JdbcBackend$SessionDef.withPreparedStatement$(JdbcBackend.scala:420)
	at slick.jdbc.JdbcBackend$BaseSession.withPreparedStatement(JdbcBackend.scala:489)
	at slick.jdbc.JdbcActionComponent$InsertActionComposerImpl.preparedInsert(JdbcActionComponent.scala:511)
	at slick.jdbc.JdbcActionComponent$InsertActionComposerImpl$MultiInsertAction.$anonfun$run$16(JdbcActionComponent.scala:530)
	at scala.collection.Iterator$$anon$10.next(Iterator.scala:461)
	at scala.collection.Iterator.foreach(Iterator.scala:943)
	at scala.collection.Iterator.foreach$(Iterator.scala:943)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1431)
	at scala.collection.generic.Growable.$plus$plus$eq(Growable.scala:62)
	at scala.collection.generic.Growable.$plus$plus$eq$(Growable.scala:53)
	at scala.collection.immutable.VectorBuilder.$plus$plus$eq(Vector.scala:668)
	at scala.collection.immutable.VectorBuilder.$plus$plus$eq(Vector.scala:645)
	at scala.collection.TraversableOnce.to(TraversableOnce.scala:348)
	at scala.collection.TraversableOnce.to$(TraversableOnce.scala:346)
	at scala.collection.AbstractIterator.to(Iterator.scala:1431)
	at scala.collection.TraversableOnce.toVector(TraversableOnce.scala:344)
	at scala.collection.TraversableOnce.toVector$(TraversableOnce.scala:344)
	at scala.collection.AbstractIterator.toVector(Iterator.scala:1431)
	at slick.jdbc.JdbcActionComponent$InsertActionComposerImpl$MultiInsertAction.run(JdbcActionComponent.scala:529)
	at slick.jdbc.JdbcActionComponent$SimpleJdbcProfileAction.run(JdbcActionComponent.scala:28)
	at slick.jdbc.JdbcActionComponent$SimpleJdbcProfileAction.run(JdbcActionComponent.scala:25)
	at slick.basic.BasicBackend$DatabaseDef$$anon$3.liftedTree1$1(BasicBackend.scala:276)
	at slick.basic.BasicBackend$DatabaseDef$$anon$3.run(BasicBackend.scala:276)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

Process finished with exit code 1

```

**Comment by mullerhai** [comment]
com.github.housepower.jdbc.statement.ClickHousePreparedInsertStatement@6c60b323: insert into `muller_test` (`a`,`b`,`c`)  values  (?,?,?)
   @Override
    public void clearParameters() throws SQLException {
        Arrays.fill(parameters, null);
    }

but   when  I  use  ”"ru.yandex.clickhouse.ClickHouseDriver" ，user slick orm mapper can insert successfully by list column struct

**Comment by mullerhai** [comment]
for the some benchmark , 
"ru.yandex.clickhouse.ClickHouseDriver" with slick  can  insert list object
"com.github.housepower.jdbc.ClickHouseDriver" with slick  only support raw sql insert but not support insert list object ,
I think  if convenient , maybe  housepower can fix up

**Comment by pan3793** [comment]
A PR #315 is raised. Please checkout the codebase and switch to that branch, then follow the doc setup in local repo or internal repo to test.
https://housepower.github.io/ClickHouse-Native-JDBC/dev/internal_release.html

**Comment by mullerhai** [comment]
> A PR #315 is raised. Please checkout the codebase and switch to that branch, then follow the doc setup in local repo or internal repo to test.
> https://housepower.github.io/ClickHouse-Native-JDBC/dev/internal_release.html

fixup so fastly ,thanks ,but I use sbt build tools for scala. project , could you. release it on maven repo

**Comment by pan3793** [comment]
> I use sbt build tools for scala. project

use `mvn clean install` to install in maven local repo, default at `~/.m2/repository`

I don't have much experience on sbt, but it should have a capability to include maven local repo.
Try below or follow sbt doc modify you build script
```
[repositories]
  local
  maven-local: file:/Users/xxxx/.m2/repository/
```

**Comment by mullerhai** [comment]
I have install the snapshot version  install  in my maven local  repo and set sbt to dependency in it 
libraryDependencies += "com.github.housepower" % "clickhouse-native-jdbc" % "2.5.4-SNAPSHOT" and  view the jar to make sure it correct version 
    public void clearParameters() throws SQLException {
        if (this.parameters != null) {
            Arrays.fill(this.parameters, (Object)null);
        }

    }

but it is also not work ,same issue 
```

15:23:24.729 [main] DEBUG s.compiler.QueryCompilerBenchmark -       assignUniqueSymbols:    1.314213 ms
15:23:24.729 [main] DEBUG s.compiler.QueryCompilerBenchmark -                inferTypes:    0.218878 ms
15:23:24.730 [main] DEBUG s.compiler.QueryCompilerBenchmark -            insertCompiler:   10.015364 ms
15:23:24.730 [main] DEBUG s.compiler.QueryCompilerBenchmark -                   codeGen:   11.632093 ms
15:23:24.731 [main] DEBUG s.compiler.QueryCompilerBenchmark -                     TOTAL:   23.180548 ms
15:23:24.734 [main] DEBUG slick.basic.BasicBackend.action - #1: MultiInsertAction [insert into "users_online" ("when","uid","make","model","duration","version")  values (?,?,?,?,?,?)]
15:23:24.906 [AsyncExecutor.default-1] INFO  r.yandex.clickhouse.ClickHouseDriver - Driver registered
15:23:25.090 [AsyncExecutor.default-1] DEBUG slick.jdbc.JdbcBackend.statement - Preparing statement: insert into "users_online" ("when","uid","make","model","duration","version")  values (?,?,?,?,?,?)
15:23:25.250 [AsyncExecutor.default-1] DEBUG c.g.h.j.s.ClickHouseStatement - close Statement
15:23:25.251 [AsyncExecutor.default-1] DEBUG c.g.h.jdbc.connect.NativeClient - flush and close socket
Exception in thread "main" java.lang.NullPointerException
	at java.util.Arrays.fill(Arrays.java:3129)
	at com.github.housepower.jdbc.statement.AbstractPreparedStatement.clearParameters(AbstractPreparedStatement.java:168)
	at slick.jdbc.LoggingPreparedStatement.clearParameters(LoggingStatement.scala:184)
	at slick.jdbc.JdbcActionComponent$InsertActionComposerImpl$MultiInsertAction.$anonfun$run$17(JdbcActionComponent.scala:531)
	at slick.jdbc.JdbcBackend$SessionDef.withPreparedStatement(JdbcBackend.scala:425)
	at slick.jdbc.JdbcBackend$SessionDef.withPreparedStatement$(JdbcBackend.scala:420)
	at slick.jdbc.JdbcBackend$BaseSession.withPreparedStatement(JdbcBackend.scala:489)
	at slick.jdbc.JdbcActionComponent$InsertActionComposerImpl.preparedInsert(JdbcActionComponent.scala:511)
	at slick.jdbc.JdbcActionComponent$InsertActionComposerImpl$MultiInsertAction.$anonfun$run$16(JdbcActionComponent.scala:530)
	at scala.collection.Iterator$$anon$10.next(Iterator.scala:461)
	at scala.collection.Iterator.foreach(Iterator.scala:943)
	at scala.collection.Iterator.foreach$(Iterator.scala:943)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1431)
	at scala.collection.generic.Growable.$plus$plus$eq(Growable.scala:62)
	at scala.collection.generic.Growable.$plus$plus$eq$(Growable.scala:53)
	at scala.collection.immutable.VectorBuilder.$plus$plus$eq(Vector.scala:668)
	at scala.collection.immutable.VectorBuilder.$plus$plus$eq(Vector.scala:645)
	at scala.collection.TraversableOnce.to(TraversableOnce.scala:348)
	at scala.collection.TraversableOnce.to$(TraversableOnce.scala:346)
	at scala.collection.AbstractIterator.to(Iterator.scala:1431)
	at scala.collection.TraversableOnce.toVector(TraversableOnce.scala:344)
	at scala.collection.TraversableOnce.toVector$(TraversableOnce.scala:344)
	at scala.collection.AbstractIterator.toVector(Iterator.scala:1431)
	at slick.jdbc.JdbcActionComponent$InsertActionComposerImpl$MultiInsertAction.run(JdbcActionComponent.scala:529)
	at slick.jdbc.JdbcActionComponent$SimpleJdbcProfileAction.run(JdbcActionComponent.scala:28)
	at slick.jdbc.JdbcActionComponent$SimpleJdbcProfileAction.run(JdbcActionComponent.scala:25)
	at slick.basic.BasicBackend$DatabaseDef$$anon$3.liftedTree1$1(BasicBackend.scala:276)
	at slick.basic.BasicBackend$DatabaseDef$$anon$3.run(BasicBackend.scala:276)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

```

**Comment by pan3793** [comment]
> `at java.util.Arrays.fill(Arrays.java:3129)`
> `at ...AbstractPreparedStatement.clearParameters(AbstractPreparedStatement.java:168)`

Your last stack trace indicate that line 168 of `AbstractPreparedStatement` invoke `Arrays#fill`, but actually after patch, the invoke line should be 169. I guess you may ref the outdated SNAPSHOT version. I will publish v2.5.4 to maven central today with this fix, please have a try if you are still facing the issue.

**Comment by mullerhai** [comment]
> > `at java.util.Arrays.fill(Arrays.java:3129)`
> > `at ...AbstractPreparedStatement.clearParameters(AbstractPreparedStatement.java:168)`
> 
> Your last stack trace indicate that line 168 of `AbstractPreparedStatement` invoke `Arrays#fill`, but actually after patch, the invoke line should be 169. I guess you may ref the outdated SNAPSHOT version. I will publish v2.5.4 to maven central today with this fix, please have a try if you are still facing the issue.

thanks ,I will try it for new version ，and will  feedback  the  running info

**Comment by mullerhai** [comment]
> > > `at java.util.Arrays.fill(Arrays.java:3129)`
> > > `at ...AbstractPreparedStatement.clearParameters(AbstractPreparedStatement.java:168)`
> > 
> > 
> > Your last stack trace indicate that line 168 of `AbstractPreparedStatement` invoke `Arrays#fill`, but actually after patch, the invoke line should be 169. I guess you may ref the outdated SNAPSHOT version. I will publish v2.5.4 to maven central today with this fix, please have a try if you are still facing the issue.
> 
> thanks ,I will try it for new version ，and will feedback the running info

sorry  ,also the same error ,do I  need give you some test code ,you can debug ? could you  show your email

**Comment by pan3793** [comment]
379377944@qq.com
