### ISSUE TITLE
batch insert ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by phenix-gao** [housepower/ClickHouse-Native-JDBC#318]
### Environment

- OS version: centos
- JDK version: 1.8
- ClickHouse Server version: 20.7.1.1
- ClickHouse Native JDBC version: 2.5.4
- (Optional) Spark version: N/A
- (Optional) Other components' version: N/A
- Sprintboot+Mybatis+ClickHouse-Native-JDBC

When I use ClickHouse-Native-JDBC client batch insert,it‘s will run  with ArrayIndexOutOfBoundsException！
it‘s not support the sql "insert into table values（？，？，？)，（？，？，？)"?

### Error logs

```
Caused by: org.apache.ibatis.type.TypeException: Error setting non null for parameter #6 with JdbcType DATE . Try setting a different JdbcType for this parameter or a different configuration property. Cause: java.sql.SQLException: Error
	at org.apache.ibatis.type.BaseTypeHandler.setParameter(BaseTypeHandler.java:71)
	at com.baomidou.mybatisplus.core.MybatisDefaultParameterHandler.setParameters(MybatisDefaultParameterHandler.java:228)
	... 91 more
Caused by: java.sql.SQLException: Error
	at com.alibaba.druid.pool.DruidDataSource.handleConnectionException(DruidDataSource.java:1774)
	at com.alibaba.druid.pool.DruidPooledConnection.handleException(DruidPooledConnection.java:134)
	at com.alibaba.druid.pool.DruidPooledStatement.checkException(DruidPooledStatement.java:81)
	at com.alibaba.druid.pool.DruidPooledPreparedStatement.setDate(DruidPooledPreparedStatement.java:393)
	at org.apache.ibatis.type.DateOnlyTypeHandler.setNonNullParameter(DateOnlyTypeHandler.java:32)
	at org.apache.ibatis.type.DateOnlyTypeHandler.setNonNullParameter(DateOnlyTypeHandler.java:27)
	at org.apache.ibatis.type.BaseTypeHandler.setParameter(BaseTypeHandler.java:69)
	... 92 more
Caused by: java.lang.ArrayIndexOutOfBoundsException: 5
	at com.github.housepower.jdbc.data.Block.setPlaceholderObject(Block.java:106)
	at com.github.housepower.jdbc.statement.ClickHousePreparedInsertStatement.setObject(ClickHousePreparedInsertStatement.java:70)
	at com.github.housepower.jdbc.statement.AbstractPreparedStatement.setDate(AbstractPreparedStatement.java:113)
	at com.alibaba.druid.filter.FilterChainImpl.preparedStatement_setDate(FilterChainImpl.java:3373)
	at com.alibaba.druid.filter.FilterAdapter.preparedStatement_setDate(FilterAdapter.java:1236)
	at com.alibaba.druid.filter.FilterChainImpl.preparedStatement_setDate(FilterChainImpl.java:3370)
	at com.alibaba.druid.filter.FilterAdapter.preparedStatement_setDate(FilterAdapter.java:1236)
	at com.alibaba.druid.filter.FilterChainImpl.preparedStatement_setDate(FilterChainImpl.java:3370)
	at com.alibaba.druid.proxy.jdbc.PreparedStatementProxyImpl.setDate(PreparedStatementProxyImpl.java:351)
	at com.alibaba.druid.pool.DruidPooledPreparedStatement.setDate(DruidPooledPreparedStatement.java:391)
	... 95 more
```

**Comment by pan3793** [comment]
Yes, we don't support multiple parameter groups. 

If you just want insert 2 records with prepared statement, just left the first group `insert into table values（?, ?, ?)` then set parameter and invoke `pstmt.addBatch()`. 

Or you can pre-assemble parameters and give a runnable SQL like `insert into table values（1, 1, 1), (2, 2, 2)` to the statement.

**Comment by phenix-gao** [comment]
Thank you. I'm doing it by give a runnable SQL like insert into table values（1, 1, 1), (2, 2, 2) to the statement
