### ISSUE TITLE
java.sql.SQLException: Broken pipe (Write failed)

### ISSUE THREAD

**Issue by gj-zhang** [housepower/ClickHouse-Native-JDBC#332]
### Environment

- OS version: 
- JDK version:
- ClickHouse Server version: 20.9.3.45
- ClickHouse Native JDBC version: 2.5.4
- (Optional) Spark version: N/A
- (Optional) Other components' version: N/A

### Error logs

```
java.sql.SQLException: Broken pipe (Write failed)
	at com.github.housepower.clickhouse.client.NativeClient.sendRequest(NativeClient.java:171)
	at com.github.housepower.clickhouse.client.NativeClient.sendData(NativeClient.java:119)
	at com.github.housepower.clickhouse.jdbc.ClickHouseConnection.sendInsertRequest(ClickHouseConnection.java:282)
	at com.github.housepower.clickhouse.jdbc.statement.ClickHousePreparedInsertStatement.close(ClickHousePreparedInsertStatement.java:142)
	at com.xx.xx.xx.xx.CkBaseSink.close(CkBaseSink.java:60)
	at org.apache.flink.api.common.functions.util.FunctionUtils.closeFunction(FunctionUtils.java:43)
	at org.apache.flink.streaming.api.operators.AbstractUdfStreamOperator.dispose(AbstractUdfStreamOperator.java:117)
	at org.apache.flink.streaming.runtime.tasks.StreamTask.disposeAllOperators(StreamTask.java:477)
	at org.apache.flink.streaming.runtime.tasks.StreamTask.invoke(StreamTask.java:378)
	at org.apache.flink.runtime.taskmanager.Task.run(Task.java:711)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.net.SocketException: Broken pipe (Write failed)
	at java.net.SocketOutputStream.socketWrite0(Native Method)
	at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:111)
	at java.net.SocketOutputStream.write(SocketOutputStream.java:134)
	at com.github.housepower.clickhouse.buffer.SocketBuffedWriter.writeBinary(SocketBuffedWriter.java:31)
	at com.github.housepower.clickhouse.serde.BinarySerializer.writeVarInt(BinarySerializer.java:49)
	at com.github.housepowerclickhouse.protocol.Request.writeTo(Request.java:29)
	at com.github.housepower.clickhouse.client.NativeClient.sendRequest(NativeClient.java:168)
```

**Comment by leachli** [comment]
have you found a solution

**Comment by leachli** [comment]
Did you find a solution？

**Comment by wenkaidang** [comment]
>Did you solve the problem?
