### ISSUE TITLE
batch insert meet nullpoint exception

### ISSUE THREAD

**Issue by mullerhai** [housepower/ClickHouse-Native-JDBC#335]
### Environment

- OS version:  mac lastest
- JDK version: jdk 11
- ClickHouse Server version:  lastest
- ClickHouse Native JDBC version: lastest
- (Optional) Spark version: N/A 3.0.2
- (Optional) Other components' version: N/A

I think maybe the spark dataframe rows size is zero 
### Error logs

```
Caused by: java.lang.NullPointerException
        at com.github.housepower.jdbc.data.type.DataTypeInt64.serializeBinary(DataTypeInt64.java:77)
        at com.github.housepower.jdbc.data.Column.write(Column.java:31)
        at com.github.housepower.jdbc.data.Block.appendRow(Block.java:93)
        at com.github.housepower.jdbc.statement.ClickHousePreparedInsertStatement.addParameters(ClickHousePreparedInsertStatement.java:162)
        at com.github.housepower.jdbc.statement.ClickHousePreparedInsertStatement.addBatch(ClickHousePreparedInsertStatement.java:95)
        at com.hw.utils.CKJDBCUtils$.saveBatchRowInsertDfToCK(CKJDBCUtils.scala:724)
        at com.hw.utils.CKJDBCUtils$.insertIterRowToCKTable(CKJDBCUtils.scala:691)
        at com.hw.utils.CKJDBCUtils$.$anonfun$initTableWithInsertDataByRDDRows$1(CKJDBCUtils.scala:428)
        at com.hw.utils.CKJDBCUtils$.$anonfun$initTableWithInsertDataByRDDRows$1$adapted(CKJDBCUtils.scala:425)
        at org.apache.spark.rdd.RDD.$anonfun$foreachPartition$2(RDD.scala:994)
        at org.apache.spark.rdd.RDD.$anonfun$foreachPartition$2$adapted(RDD.scala:994)
        at org.apache.spark.SparkContext.$anonfun$runJob$5(SparkContext.scala:2154)
        at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
        at org.apache.spark.scheduler.Task.run(Task.scala:127)
        at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:462)
        at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1377)
        at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:465)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
```

**Comment by TimmannaC** [comment]
> Please provide reproducible code.

"""
I tried with the com.github.housepower:clickhouse-integration-spark_2.12:2.5.4 jar but unable to resolve the com.github.housepower.jdbc.ClickHouseDriver class Hence I am trying using com.github.housepower:clickhouse-native-jdbc:2.5.4 but facing issue while writing to table 
"""

from pyspark.sql.functions import *
from pyspark.sql.types import *
from pyspark.sql import *
from pyspark.sql.functions import lit, udf, expr, concat, col, explode, split, explode_outer
from pyspark.sql import functions as F
import json


connectionString = "<<EVENTHUB_END_POINT>>"

eventHubConfig = {
  'eventhubs.connectionString':sc._jvm.org.apache.spark.eventhubs.EventHubsUtils.encrypt(connectionString),
  'eventhubs.consumerGroup': "$default"
}

schema = spark.read.json("/tmp/test/eventhub.json").schema
  
df = (
    spark.read
    .format("eventhubs")
    .options(**eventHubConfig)
    .load()
    .selectExpr("cast(body as string) as body_str")
)


username = "default"
password = ""

clickhouseurl = "jdbc:clickhouse://xx.xx.xx.xx:9000/default"

connectionProp = {
  "user" : username,
  "password" : password,
  "driver" : "com.github.housepower.jdbc.ClickHouseDriver"
}

df.write.jdbc(url=clickhouseurl,table="default.ntorq_streaming",mode="append",properties=connectionProp)

Below is the error what I am getting 

org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 1.0 failed 4 times, most recent failure: Lost task 0.3 in stage 1.0 (TID 4) (10.139.64.4 executor 0): java.lang.NullPointerException
---------------------------------------------------------------------------
Py4JJavaError                             Traceback (most recent call last)
<command-921682319246573> in <module>
----> 1 df3.write.jdbc(url=clickhouseurl,table="default.ntorq_streaming",mode="append",properties=connectionProp)

/databricks/spark/python/pyspark/sql/readwriter.py in jdbc(self, url, table, mode, properties)
   1469         for k in properties:
   1470             jprop.setProperty(k, properties[k])
-> 1471         self.mode(mode)._jwrite.jdbc(url, table, jprop)
   1472 
   1473 

/databricks/spark/python/lib/py4j-0.10.9-src.zip/py4j/java_gateway.py in __call__(self, *args)
   1302 
   1303         answer = self.gateway_client.send_command(command)
-> 1304         return_value = get_return_value(
   1305             answer, self.gateway_client, self.target_id, self.name)
   1306 

/databricks/spark/python/pyspark/sql/utils.py in deco(*a, **kw)
    108     def deco(*a, **kw):
    109         try:
--> 110             return f(*a, **kw)
    111         except py4j.protocol.Py4JJavaError as e:
    112             converted = convert_exception(e.java_exception)

/databricks/spark/python/lib/py4j-0.10.9-src.zip/py4j/protocol.py in get_return_value(answer, gateway_client, target_id, name)
    324             value = OUTPUT_CONVERTER[type](answer[2:], gateway_client)
    325             if answer[1] == REFERENCE_TYPE:
--> 326                 raise Py4JJavaError(
    327                     "An error occurred while calling {0}{1}{2}.\n".
    328                     format(target_id, ".", name), value)

Py4JJavaError: An error occurred while calling o572.jdbc.
: org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 1.0 failed 4 times, most recent failure: Lost task 0.3 in stage 1.0 (TID 4) (10.139.64.4 executor 0): java.lang.NullPointerException
	at com.github.housepower.jdbc.data.type.DataTypeInt8.serializeBinary(DataTypeInt8.java:74)
	at com.github.housepower.jdbc.data.Column.write(Column.java:31)
	at com.github.housepower.jdbc.data.Block.appendRow(Block.java:93)
	at com.github.housepower.jdbc.statement.ClickHousePreparedInsertStatement.addParameters(ClickHousePreparedInsertStatement.java:162)
	at com.github.housepower.jdbc.statement.ClickHousePreparedInsertStatement.addBatch(ClickHousePreparedInsertStatement.java:95)
	at org.apache.spark.sql.execution.datasources.jdbc.JdbcUtils$.savePartition(JdbcUtils.scala:683)
	at org.apache.spark.sql.execution.datasources.jdbc.JdbcUtils$.$anonfun$saveTable$1(JdbcUtils.scala:856)
	at org.apache.spark.sql.execution.datasources.jdbc.JdbcUtils$.$anonfun$saveTable$1$adapted(JdbcUtils.scala:854)
	at org.apache.spark.rdd.RDD.$anonfun$foreachPartition$2(RDD.scala:1025)
	at org.apache.spark.rdd.RDD.$anonfun$foreachPartition$2$adapted(RDD.scala:1025)
	at org.apache.spark.SparkContext.$anonfun$runJob$2(SparkContext.scala:2498)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:68)
	at org.apache.spark.scheduler.Task.doRunTask(Task.scala:148)
	at org.apache.spark.scheduler.Task.run(Task.scala:117)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$10(Executor.scala:732)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1643)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:735)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by pan3793** [comment]
I'm not familiar with spark python api, and you should also register clickhouse dialect before using it.
https://github.com/housepower/ClickHouse-Native-JDBC/blob/a475e1d28a6e88fd9ea71b9c1b4a25ec5ab278eb/clickhouse-integration/clickhouse-integration-spark/src/test/scala/com.github.housepower.jdbc.spark/SparkOnClickHouseITest.scala#L32-L33

**Comment by TimmannaC** [comment]
> > I tried with the com.github.housepower:clickhouse-integration-spark_2.12:2.5.4 jar but unable to resolve the com.github.housepower.jdbc.ClickHouseDriver class
> 
> It's by design. `clickhouse-integration-spark` is not bind to `clickhouse-native-jdbc` driver, you can use it with yandex driver also.

Hi Pan,
thank you for your respone.
I tried with only yandex driver but its behaviour is very wearied it is only writing 1 record from a batch of 100 every time. 
can you please point me to some reference examples on using yandex driver and clickhouse-integration-spark driver to write to clickhouse.

**Comment by TimmannaC** [comment]
> Are you trying to write `null` values into an `Int8` column? If yes, change the column type to `Nullable(Int8)`

Hello Pan,
Thank you for pointing out the issue.
I have made couple of columns nullable and its working now but still I am not able to insert whole dataframe to table.
eg : my spark dataframe has 100 records when I write to clickhouse only 1 record is getting inserted.
Is there any property i need to add to overwrite this behavior?

Below is my table ddl.
CREATE TABLE  IF NOT EXISTS default.streaming_tbl
(
timestamp DateTime Codec(DoubleDelta, LZ4),
userid UInt64 Codec(T64, LZ4),
userVehicleId UInt64 Codec(T64, LZ4),
name LowCardinality(String)
)
ENGINE = ReplacingMergeTree()
PARTITION BY toYYYYMM(timestamp)
ORDER BY (timestamp,userVehicleId);

Thanks
