### ISSUE TITLE
spark writes exception "Syntax error: failed at position 60072 (end of query): . Expected one of: storage definition, ENGINE, AS. "

### ISSUE THREAD

**Issue by chrislusf** [housepower/ClickHouse-Native-JDBC#341]
### Environment

- OS version: linux
- JDK version: jdk8
- ClickHouse Server version:  version 20.12.4
- ClickHouse Native JDBC version:  clickhouse-native-jdbc-shaded-2.5.4.jar
- (Optional) Spark version: 2.4.3
- (Optional) Other components' version: clickhouse-integration-spark_2.11-2.5.4.jar

### Error logs

```
data.write.format("jdbc").mode("overwrite").option("driver", "com.github.housepower.jdbc.ClickHouseDriver").option("url", "jdbc:clickhouse://xxx:yyyy").option("user", "default").option("password", "").option("dbtable", "db.test_target").option("truncate", "true").option("batchsize", 1000).option("isolationLevel", "NONE").save
Error: com.github.housepower.jdbc.ClickHouseSQLException: DB::ExceptionDB::Exception: Syntax error: failed at position 60072 (end of query): . Expected one of: storage definition, ENGINE, AS. Stack trace:


0. DB::parseQueryAndMovePosition(DB::IParser&, char const*&, char const*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, bool, unsigned long, unsigned long) @ 0xe997949 in /usr/lib/debug/usr/bin/clickhouse

1. DB::executeQueryImpl(char const*, char const*, DB::Context&, bool, DB::QueryProcessingStage::Enum, bool, DB::ReadBuffer*) @ 0xdef9c45 in /usr/lib/debug/usr/bin/clickhouse

2. DB::executeQuery(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, DB::Context&, bool, DB::QueryProcessingStage::Enum, bool) @ 0xdef98bd in /usr/lib/debug/usr/bin/clickhouse

3. DB::TCPHandler::runImpl() @ 0xe5cf926 in /usr/lib/debug/usr/bin/clickhouse

4. DB::TCPHandler::run() @ 0xe5dbe27 in /usr/lib/debug/usr/bin/clickhouse

5. Poco::Net::TCPServerConnection::start() @ 0x10d85cff in /usr/lib/debug/usr/bin/clickhouse
  at com.github.housepower.jdbc.stream.ClickHouseQueryResult.header(ClickHouseQueryResult.java:43)

  at com.github.housepower.jdbc.statement.ClickHouseStatement.executeUpdate(ClickHouseStatement.java:93)

  at org.apache.spark.sql.execution.datasources.jdbc.JdbcUtils$.createTable(JdbcUtils.scala:859)

  at org.apache.spark.sql.execution.datasources.jdbc.JdbcRelationProvider.createRelation(JdbcRelationProvider.scala:81)

  at org.apache.spark.sql.execution.datasources.SaveIntoDataSourceCommand.run(SaveIntoDataSourceCommand.scala:54)

  at org.apache.spark.sql.execution.command.ExecutedCommandExec.sideEffectResult$lzycompute(commands.scala:70)

  at org.apache.spark.sql.execution.command.ExecutedCommandExec.sideEffectResult(commands.scala:68)

  at org.apache.spark.sql.execution.command.ExecutedCommandExec.doExecute(commands.scala:86)

  at org.apache.spark.sql.execution.SparkPlan$$anonfun$execute$1.apply(SparkPlan.scala:131)

  at org.apache.spark.sql.execution.SparkPlan$$anonfun$execute$1.apply(SparkPlan.scala:127)

  at org.apache.spark.sql.execution.SparkPlan$$anonfun$executeQuery$1.apply(SparkPlan.scala:155)

  at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)

  at org.apache.spark.sql.execution.SparkPlan.executeQuery(SparkPlan.scala:152)

  at org.apache.spark.sql.execution.SparkPlan.execute(SparkPlan.scala:127)

  at org.apache.spark.sql.execution.QueryExecution.toRdd$lzycompute(QueryExecution.scala:106)

  at org.apache.spark.sql.execution.QueryExecution.toRdd(QueryExecution.scala:106)

  at org.apache.spark.sql.DataFrameWriter$$anonfun$runCommand$1.apply(DataFrameWriter.scala:676)

  at org.apache.spark.sql.DataFrameWriter$$anonfun$runCommand$1.apply(DataFrameWriter.scala:676)

  at org.apache.spark.sql.execution.SQLExecution$$anonfun$withNewExecutionId$1.apply(SQLExecution.scala:88)

  at org.apache.spark.sql.execution.SQLExecution$.withSQLConfPropagated(SQLExecution.scala:135)

  at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:73)

  at org.apache.spark.sql.DataFrameWriter.runCommand(DataFrameWriter.scala:676)

  at org.apache.spark.sql.DataFrameWriter.saveToV1Source(DataFrameWriter.scala:285)

  at org.apache.spark.sql.DataFrameWriter.save(DataFrameWriter.scala:271)

  ... 47 elided
```

### Steps to reproduce

In a scala shell:
```
    import org.apache.spark.sql.jdbc.ClickHouseDialect;
    import org.apache.spark.sql.jdbc.JdbcDialects;

    JdbcDialects.registerDialect(ClickHouseDialect)

    val data = spark.sql("select * from some_table ");

    data.write.format("jdbc").mode("overwrite").option("driver", "com.github.housepower.jdbc.ClickHouseDriver").option("url", "jdbc:clickhouse://phx3-p5:25604").option("user", "default").option("password", "").option("dbtable", "test_target").option("truncate", "true").option("batchsize", 10000).option("isolationLevel", "NONE").save


```

**Comment by chrislusf** [comment]
Updated. Found out the previous error was due to using HTTP instead of TCP port.

But with the right TCP port, the code instantly get into the above exception.

**Comment by chrislusf** [comment]
FYI: found solution in 

https://github.com/housepower/ClickHouse-Native-JDBC/issues/296
https://github.com/housepower/ClickHouse-Native-JDBC/issues/313
