### ISSUE TITLE
Port can't be use when jar been uploaded on to the server

### ISSUE THREAD

**Issue by TheXs** [housepower/ClickHouse-Native-JDBC#342]
### Environment

- OS version: 
- JDK version:1.8
- ClickHouse Server version: 20.4.4.18
- ClickHouse Native JDBC version:1.8-stable-SNAPSHOT
- (Optional) Spark version: N/A
- (Optional) Other components' version: N/A

### Error logs
[root@192 /]# java  -jar clickhouse-native-jdbc-1.8-stable-SNAPSHOT-jar-with-dependencies.jar
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Exception in thread "main" java.lang.RuntimeException: ru.yandex.clickhouse.except.ClickHouseUnknownException: ClickHouse exception, code: 1002, host: 192.168.xx.xxx, port: 9000; Port 9000 is for clickhouse-client program.
You must use port 8123 for HTTP.

	at ru.yandex.clickhouse.ClickHouseConnectionImpl.initTimeZone(ClickHouseConnectionImpl.java:99)
	at ru.yandex.clickhouse.ClickHouseConnectionImpl.<init>(ClickHouseConnectionImpl.java:80)
	at ru.yandex.clickhouse.ClickHouseDriver.connect(ClickHouseDriver.java:55)
	at ru.yandex.clickhouse.ClickHouseDriver.connect(ClickHouseDriver.java:47)
	at ru.yandex.clickhouse.ClickHouseDriver.connect(ClickHouseDriver.java:29)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:270)
	at examples.BatchQuery.main(BatchQuery.java:30)

```
paste your error logs here
```
[root@192 /]# java  -jar clickhouse-native-jdbc-1.8-stable-SNAPSHOT-jar-with-dependencies.jar
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Exception in thread "main" java.lang.RuntimeException: ru.yandex.clickhouse.except.ClickHouseUnknownException: ClickHouse exception, code: 1002, host: 192.168.xx.xxx, port: 9000; Port 9000 is for clickhouse-client program.
You must use port 8123 for HTTP.

	at ru.yandex.clickhouse.ClickHouseConnectionImpl.initTimeZone(ClickHouseConnectionImpl.java:99)
	at ru.yandex.clickhouse.ClickHouseConnectionImpl.<init>(ClickHouseConnectionImpl.java:80)
	at ru.yandex.clickhouse.ClickHouseDriver.connect(ClickHouseDriver.java:55)
	at ru.yandex.clickhouse.ClickHouseDriver.connect(ClickHouseDriver.java:47)
	at ru.yandex.clickhouse.ClickHouseDriver.connect(ClickHouseDriver.java:29)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:270)
	at examples.BatchQuery.main(BatchQuery.java:30)
### Steps to reproduce
The main method could be run on my local machine, when I packaged it to a executable jar and uploaded it on to the server where my ck server was and run, I got the error that I posted above.

### Other descriptions
Hi, there. Just had some senses on using ck and I am currently trying to do some batch insert works. It was ok when I run the main method with my IDE, but when I packaged it using maven and run on the ck-server site, it turns on that even I am not using ck-client. Best regards if anyone can help. Cheers!

**Comment by sundy-li** [comment]
You are using clickhouse-jdbc not native-jdbc

**Comment by TheXs** [comment]
I used clickhouse-jdbc for some other functions, can't native-jdbc and clickhouse-jdbc be co-existing? Thanks for reply anw :)

**Comment by TheXs** [comment]
I have figured out the problem, thx for your assistance!
