### ISSUE TITLE
Exception in Kafka Connect

### ISSUE THREAD

**Issue by akamensky** [housepower/ClickHouse-Native-JDBC#347]
### Environment

- OS version: Centos 7.5
- JDK version: AdopOpenJDK 11.0.4
- ClickHouse Server version: `21.5.5.12`
- ClickHouse Native JDBC version: `2.5.4-shaded`
- (Optional) Spark version: N/A
- (Optional) Other components' version: kafkaconnect version `6.1.1-2.12`

### Error logs

```
2021-05-27 11:39:24.043 +0800 [task-thread-sink-clickhouse-data-0] [WARN ] io.confluent.connect.jdbc.sink.JdbcSinkTask - Write of 500 records failed, remainingRetries=0
java.sql.SQLFeatureNotSupportedException
	at com.github.housepower.jdbc.wrapper.SQLPreparedStatement.setDate(SQLPreparedStatement.java:187)
	at io.confluent.connect.jdbc.dialect.GenericDatabaseDialect.maybeBindLogical(GenericDatabaseDialect.java:1652)
	at io.confluent.connect.jdbc.dialect.GenericDatabaseDialect.bindField(GenericDatabaseDialect.java:1573)
	at io.confluent.connect.jdbc.dialect.DatabaseDialect.bindField(DatabaseDialect.java:608)
	at io.confluent.connect.jdbc.sink.PreparedStatementBinder.bindField(PreparedStatementBinder.java:186)
	at io.confluent.connect.jdbc.sink.PreparedStatementBinder.bindNonKeyFields(PreparedStatementBinder.java:172)
	at io.confluent.connect.jdbc.sink.PreparedStatementBinder.bindRecord(PreparedStatementBinder.java:103)
	at io.confluent.connect.jdbc.sink.BufferedRecords.flush(BufferedRecords.java:184)
	at io.confluent.connect.jdbc.sink.JdbcDbWriter.write(JdbcDbWriter.java:80)
	at io.confluent.connect.jdbc.sink.JdbcSinkTask.put(JdbcSinkTask.java:84)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:586)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:329)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:232)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:201)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:189)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:238)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

### Other descriptions
Looks like an issue with using prepared statements and setDate, but not sure which field this relates to. Table has 2 columns with date related data one is DateTime, another is Date.

Same setup (table definition) and same exact data works fine with official driver. We however would like to make it work with native as throughput is much better and load is much lower.

**Comment by pan3793** [comment]
Thanks for report, I will take a look.

**Comment by akamensky** [comment]
Looking at the code seems that all methods in prepared statement class are "unimplemented". However we have other tables written by kafkaconnect that working just fine, which means for some reason driver doesn't use prepared statements there?

**Comment by pan3793** [comment]
`SQLPreparedStatement` just a interface, see implementation in subclasses

**Comment by pan3793** [comment]
The broken method is 
```
    /**
     * Sets the designated parameter to the given <code>java.sql.Time</code> value,
     * using the given <code>Calendar</code> object.  The driver uses
     * the <code>Calendar</code> object to construct an SQL <code>TIME</code> value,
     * which the driver then sends to the database.  With
     * a <code>Calendar</code> object, the driver can calculate the time
     * taking into account a custom timezone.  If no
     * <code>Calendar</code> object is specified, the driver uses the default
     * timezone, which is that of the virtual machine running the application.
     *
     * @param parameterIndex the first parameter is 1, the second is 2, ...
     * @param x the parameter value
     * @param cal the <code>Calendar</code> object the driver will use
     *            to construct the time
     * @exception SQLException if parameterIndex does not correspond to a parameter
     * marker in the SQL statement; if a database access error occurs or
     * this method is called on a closed <code>PreparedStatement</code>
     * @since 1.2
     */
    void setDate(int parameterIndex, java.sql.Date x, Calendar cal) throws SQLException;
```

**Comment by pan3793** [comment]
v2.5.5 is out with the patch, it will available in maven central in few hours.

**Comment by akamensky** [comment]
Thanks, that was quick!

**Comment by akamensky** [comment]
Verified with 2.5.5.
