### ISSUE TITLE
No array column but get "Array index out of range: 1048576"

### ISSUE THREAD

**Issue by sky9611** [housepower/ClickHouse-Native-JDBC#378]
### Environment

- OS version: Ubuntu 20.04.3 LTS
- JDK version: 1.8.0_272
- ClickHouse Server version: 21.8.5.7
- ClickHouse Native JDBC version: 2.5.6
- (Optional) Spark version: 2.4
- (Optional) Other components' version: N/A

### Error logs

```
java.lang.ArrayIndexOutOfBoundsException: Array index out of range: 1048576
	at net.jpountz.util.SafeUtils.checkRange(SafeUtils.java:24)

	at net.jpountz.util.SafeUtils.checkRange(SafeUtils.java:32)

	at net.jpountz.lz4.LZ4JavaSafeCompressor.compress(LZ4JavaSafeCompressor.java:141)

	at net.jpountz.lz4.LZ4Compressor.compress(LZ4Compressor.java:95)

	at com.github.housepower.jdbc.buffer.CompressedBuffedWriter.flushToTarget(CompressedBuffedWriter.java:75)

	at com.github.housepower.jdbc.serde.BinarySerializer.flushToTarget(BinarySerializer.java:112)

	at com.github.housepower.jdbc.connect.NativeClient.disconnect(NativeClient.java:153)

	at com.github.housepower.jdbc.ClickHouseConnection.close(ClickHouseConnection.java:141)

	at org.apache.spark.sql.execution.datasources.jdbc.JdbcUtils$.savePartition(JdbcUtils.scala:714)

	at org.apache.spark.sql.execution.datasources.jdbc.JdbcUtils$$anonfun$saveTable$1.apply(JdbcUtils.scala:838)

	at org.apache.spark.sql.execution.datasources.jdbc.JdbcUtils$$anonfun$saveTable$1.apply(JdbcUtils.scala:838)

	at org.apache.spark.rdd.RDD$$anonfun$foreachPartition$1$$anonfun$apply$28.apply(RDD.scala:980)

	at org.apache.spark.rdd.RDD$$anonfun$foreachPartition$1$$anonfun$apply$28.apply(RDD.scala:980)

	at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:2158)

	at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:2158)

	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)

	at org.apache.spark.scheduler.Task.run(Task.scala:123)

	at org.apache.spark.executor.Executor$TaskRunner$$anonfun$10.apply(Executor.scala:409)

	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1360)

	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:415)

	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)

	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)

	at java.lang.Thread.run(Thread.java:748)
```

### Steps to reproduce
Using spark to ingest a large dataframe(> 100M rows) with many columns(>5000) into Clickhouse.

Here is the code I use:

``` Scala
df.write.format("jdbc").mode("append").
    option("driver","com.github.housepower.jdbc.ClickHouseDriver").
    option("url", jdbcUrl).
    option("user", "***").
    option("password", "***").
    option("dbtable", target_table).
    option("truncate", "true").
    option("batchsize", 100000).
    option("isolationLevel", "NONE").
    option("numPartitions", "128").save
```

### Other descriptions

Based on this [issue](https://github.com/housepower/ClickHouse-Native-JDBC/issues/330), this could be caused by inserting array column. But the dataframe I inserted contains only StringType, timestamp and LongType.

I've also tried to do some investigation on the these source codes: 
- [CompressedBuffedWriter.java](https://github.com/housepower/ClickHouse-Native-JDBC/blob/21cbb5ebab0a5cab54174e049c268ab8bc6da032/clickhouse-native-jdbc/src/main/java/com/github/housepower/buffer/CompressedBuffedWriter.java)
- [LZ4Compressor.java](https://github.com/lz4/lz4-java/blob/812d2e27489995645d878c9fb2ddcb83e54cc7d2/src/java/net/jpountz/lz4/LZ4Compressor.java)
- [SafeUtils.java](https://github.com/lz4/lz4-java/blob/master/src/java/net/jpountz/util/SafeUtils.java)

Unfortunately, I still couldn't find the cause.

**Comment by sundy-li** [comment]
Good search, can you try to modify the compression codes from:
```
 int res = lz4Compressor.compress(writtenBuf, 0, position, compressedBuffer, COMPRESSION_HEADER_LENGTH + CHECKSUM_LENGTH, compressedBuffer.length);
```

to 

```
  int res = lz4Compressor.compress(writtenBuf, 0, position, compressedBuffer, COMPRESSION_HEADER_LENGTH + CHECKSUM_LENGTH, maxLen);
```

I think this may be the reason.

**Comment by sky9611** [comment]
Re-ran the pipeline for the whole night with the new-built Jar, the problem seems to be persisted.

In fact, I found in the code of the [latest release](https://github.com/housepower/ClickHouse-Native-JDBC/releases/tag/v2.5.6),  it used 

``` java
int res = lz4Compressor.compress(writtenBuf, 0, position, compressedBuffer, 9 + 16);
```

Based on [LZ4Compressor.java](https://github.com/lz4/lz4-java/blob/812d2e27489995645d878c9fb2ddcb83e54cc7d2/src/java/net/jpountz/lz4/LZ4Compressor.java), it is an overloading method of `compress`:

``` java
public final int compress(byte[] src, int srcOff, int srcLen, byte[] dest, int destOff) {
    return compress(src, srcOff, srcLen, dest, destOff, dest.length - destOff);
}
```

So it's same as

``` java
int res = lz4Compressor.compress(writtenBuf, 0, position, compressedBuffer, 9 + 16, compressedBuffer.length - (9 + 16));
```

Since `byte[] compressedBuffer = new byte[maxLen + 9 + 16]; `, so **Yes**, `maxDestLen` **must be** `maxLen`. The code in master branch may need to be modified.

But still, we didn't find the root cause of "**Array index out of range: 1048576**"
