### ISSUE TITLE
"select null as aa,null as bb" is not supported in ClickHouse-Native-JDBC

### ISSUE THREAD

**Issue by wallace-clickhouse** [housepower/ClickHouse-Native-JDBC#389]
### Environment

- OS version: SUSE 12.5
- JDK version:1.8
- ClickHouse Server version: 20.3.2.1
- ClickHouse Native JDBC version:2.5.4

### Error logs
Exception in thread "main" java.lang.UnsupportedOperationException: Unknown compression method: 108
	at com.github.housepower.jdbc.buffer.CompressedBuffedReader.readCompressedData(CompressedBuffedReader.java:94)
	at com.github.housepower.jdbc.buffer.CompressedBuffedReader.readBinary(CompressedBuffedReader.java:50)
	at com.github.housepower.jdbc.serde.BinaryDeserializer.readUTF8StringBinary(BinaryDeserializer.java:90)
	at com.github.housepower.jdbc.data.Block.readFrom(Block.java:40)
	at com.github.housepower.jdbc.protocol.DataResponse.readFrom(DataResponse.java:32)
	at com.github.housepower.jdbc.protocol.Response.readFrom(Response.java:33)
	at com.github.housepower.jdbc.connect.NativeClient.receiveResponse(NativeClient.java:178)
	at com.github.housepower.jdbc.connect.NativeClient.lambda$receiveQuery$0(NativeClient.java:135)
	at com.github.housepower.jdbc.stream.ClickHouseQueryResult.consumeDataResponse(ClickHouseQueryResult.java:89)
	at com.github.housepower.jdbc.stream.ClickHouseQueryResult.access$100(ClickHouseQueryResult.java:26)
	at com.github.housepower.jdbc.stream.ClickHouseQueryResult$1.fill(ClickHouseQueryResult.java:65)
	at com.github.housepower.jdbc.stream.ClickHouseQueryResult$1.hasNext(ClickHouseQueryResult.java:55)
	at com.github.housepower.jdbc.ClickHouseResultSet.fetchBlock(ClickHouseResultSet.java:439)
	at com.github.housepower.jdbc.ClickHouseResultSet.next(ClickHouseResultSet.java:408)

### Steps to reproduce
Use the ClickHouse-Native-JDBC (2.5.4) driver to access the ClickHouse database, construct the query "select null as aa,null as bb", and use the ResultSet to store the query result. After the query is executed, the preceding error is reported.

### Other descriptions
At first, I used ClickHouse-Native-JDBC 2.2. When I used the “select null as aa” syntax, an error message was displayed, and the error message was " Exception in thread "main" java.sql.SQLException: Unknown data type family:Nothing". Later, when I upgraded to 2.5.4, If one "null as xx" is displayed in the query result, no problem occurs. If multiple "null as xx" are displayed, an error message is displayed, as shown in the Error logs.

**Comment by wallace-clickhouse** [comment]
I checked the source code and found that the clickhouse-native-jdbc implementation is highly similar to the clickhouse-client which is implemented in C++, while clickhouse-client supports the syntax of "select null as aa,null as bb" well. 
Therefore, it is suspected that the bug is caused by clickhouse-native-jdbc.Does the community have any plans for restoration?

**Comment by sundy-li** [comment]
Yes, it's buggy in this JDBC client.

```
SELECT
    NULL AS aa,
    NULL AS bb,
    toTypeName(aa)

Query id: cebfe071-2c24-451c-8a8e-e4229e193c70

┌─aa───┬─bb───┬─toTypeName(NULL)──┐
│ ᴺᵁᴸᴸ │ ᴺᵁᴸᴸ │ Nullable(Nothing) │
└──────┴──────┴───────────────────┘

1 rows in set. Elapsed: 0.003 sec.
```

I think we may need to add Nothing DataType support in jdbc client.  Do you have an interest in submitting a pr to improve this ?

**Comment by wallace-clickhouse** [comment]
Yeah, I'm glad to contribute to the community, and I'm trying to fix it right now. Actually, ClickHouse-Native-JDBC already supports the Nothing DataType. However, when the query result is received and parsed, if null is encountered, the byte-by-byte phase is confused. Can you provide some guidance?

**Comment by wallace-clickhouse** [comment]
@sundy-li Hello,
My problem is that I don't know the encoding rules for every byte in the received packet, so I can't correctly parse and identify the starting position and ending position of the "null as aa" column in the result set. 
I have tried a lot but couldn't fix this bug. could you please give us a fix？Thank you very much!

**Comment by wallace-clickhouse** [comment]
@sundy-li 
Thank you very much, the problem is well fixed.

**Comment by wallace-clickhouse** [comment]
@sundy-li @pan3793 
Could the community launch a release package based on the fixed version?
Thank you!

**Comment by sundy-li** [comment]
2.6.3 is releasing in progress.

**Comment by wallace-clickhouse** [comment]
@sundy-li 
Thank you, and firmly believe that this driver will become more and more perfect.
