### ISSUE TITLE
MyBatis Batch Insert Exception

### ISSUE THREAD

**Issue by zyfbbd** [housepower/ClickHouse-Native-JDBC#416]
### Environment

- JDK version:1.8
- MyBatis: 3.4.5
- ClickHouse Server version: 20.12.5.14
- ClickHouse Native JDBC version: 2.5.2
- (Optional) Flink version: N/A 1.14.4

### Error logs
Caused by: org.apache.ibatis.type.TypeException: Error setting non null for parameter #25 with JdbcType null . Try setting a different JdbcType for this parameter or a different configuration property. Cause: java.sql.SQLException: Error
	at org.apache.ibatis.type.BaseTypeHandler.setParameter(BaseTypeHandler.java:55)
	at org.apache.ibatis.scripting.defaults.DefaultParameterHandler.setParameters(DefaultParameterHandler.java:87)
	... 12 more
Caused by: java.sql.SQLException: Error
	at com.alibaba.druid.pool.DruidDataSource.handleConnectionException(DruidDataSource.java:1811)
	at com.alibaba.druid.pool.DruidPooledConnection.handleException(DruidPooledConnection.java:137)
	at com.alibaba.druid.pool.DruidPooledStatement.checkException(DruidPooledStatement.java:93)
	at com.alibaba.druid.pool.DruidPooledPreparedStatement.setInt(DruidPooledPreparedStatement.java:316)
	at org.apache.ibatis.type.IntegerTypeHandler.setNonNullParameter(IntegerTypeHandler.java:31)
	at org.apache.ibatis.type.IntegerTypeHandler.setNonNullParameter(IntegerTypeHandler.java:26)
	at org.apache.ibatis.type.BaseTypeHandler.setParameter(BaseTypeHandler.java:53)
	... 13 more
Caused by: java.lang.ArrayIndexOutOfBoundsException: 24
	at com.github.housepower.jdbc.data.Block.setPlaceholderObject(Block.java:106)
	at com.github.housepower.jdbc.statement.ClickHousePreparedInsertStatement.setObject(ClickHousePreparedInsertStatement.java:70)
	at com.github.housepower.jdbc.statement.AbstractPreparedStatement.setInt(AbstractPreparedStatement.java:77)
	at com.alibaba.druid.pool.DruidPooledPreparedStatement.setInt(DruidPooledPreparedStatement.java:314)
	... 16 more

### Other descriptions
The third driver clickhouse-native-jdbc not support batch insert use mybatis ?

**Comment by sundy-li** [comment]
It did not support mybatis.

**Comment by zyfbbd** [comment]
> It did not support mybatis.

now I can select use mybatis and insert one row,but cann`t batch insert follow example.
<insert id="batchInsertMdProduct">
        insert into table
        <include refid="Base_Column_List"/>
        values
        <foreach collection="list" open="" close="" separator="," item="item">
        
        </foreach>
</insert>

How can I implement batch insert data to clickhouse？
