### ISSUE TITLE
Error in sending request.

### ISSUE THREAD

**Issue by ggservice007** [housepower/ClickHouse-Native-JDBC#52]
```java
Class.forName("com.github.housepower.jdbc.ClickHouseDriver");
    Connection connection = DriverManager.getConnection("jdbc:clickhouse://115.29.37.214:9000");
    Statement stmt = connection.createStatement();
    ResultSet rs = stmt.executeQuery("SELECT (number % 3 + 1) as n, sum(number) FROM numbers(10000000) GROUP BY n");

    while (rs.next()) {
      System.out.println(rs.getInt(1) + "\t" + rs.getLong(2));
    }
```

```cmd
Exception in thread "main" java.sql.SQLException: Broken pipe (Write failed)
	at com.github.housepower.jdbc.connect.PhysicalConnection.disPhysicalConnection(PhysicalConnection.java:103)
	at com.github.housepower.jdbc.ClickHouseConnection.getHealthyPhysicalConnection(ClickHouseConnection.java:146)
```

**Comment by zhang2014** [comment]
Please provide more details on this issue:
- ClickHouse-Server version
- ClickHouse-Native-JDBC version

thanks :)

**Comment by ggservice007** [comment]
It's my fault.  Error in sever configure.

Thanks a lot.

**Comment by kung-foo** [comment]
@ggservice007 you probably shouldn't include your actual server address since you are open to the internet with no authentication.
