### ISSUE TITLE
Support SQLConnection.getCatalog API

### ISSUE THREAD

**Issue by shanling2004** [housepower/ClickHouse-Native-JDBC#75]
we try to integrate this clickhouse JDBC connection with c3p0 data source pool. But we encounter the below issue

```
java.sql.SQLFeatureNotSupportedException
	at com.github.housepower.jdbc.wrapper.SQLConnection.getCatalog(SQLConnection.java:88)
	at com.mchange.v2.c3p0.impl.NewPooledConnection.<init>(NewPooledConnection.java:108)
	at com.mchange.v2.c3p0.WrapperConnectionPoolDataSource.getPooledConnection(WrapperConnectionPoolDataSource.java:159)
	at com.mchange.v2.c3p0.WrapperConnectionPoolDataSource.getPooledConnection(WrapperConnectionPoolDataSource.java:132)
	at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool$1PooledConnectionResourcePoolManager.acquireResource(C3P0PooledConnectionPool.java:137)
	at com.mchange.v2.resourcepool.BasicResourcePool.doAcquire(BasicResourcePool.java:1014)
	at com.mchange.v2.resourcepool.BasicResourcePool.access$800(BasicResourcePool.java:32)
	at com.mchange.v2.resourcepool.BasicResourcePool$AcquireTask.run(BasicResourcePool.java:1810)
	at com.mchange.v2.async.ThreadPoolAsynchronousRunner$PoolThread.run(ThreadPoolAsynchronousRunner.java:547)

```

related source code
```
 private final ComboPooledDataSource cpds = new ComboPooledDataSource();

  public Connection getConnection() throws SQLException {
    return cpds.getConnection();
  }

  C3poDataSource() {
    try {
      cpds.setDriverClass("com.github.housepower.jdbc.ClickHouseDriver");
      cpds.setJdbcUrl("jdbc:clickhouse://10.8.121.33:9000");
      cpds.setMinPoolSize(10);
      cpds.setMaxPoolSize(10);

    } catch (PropertyVetoException e) {
      // handle the exception
    }
  }
```

For related source code, https://github.com/housepower/ClickHouse-Native-JDBC/blob/master/src/main/java/com/github/housepower/jdbc/wrapper/SQLConnection.java#L87-L89

**Comment by sw1991913** [comment]
when i  use druid  or hikari   datasource，depend this:
java.sql.SQLFeatureNotSupportedException
	at com.github.housepower.jdbc.wrapper.SQLConnection.getCatalog(SQLConnection.java:88)
	at com.alibaba.druid.pool.DruidPooledConnection.getCatalog(DruidPooledConnection.java:920)
	at com.alibaba.druid.pool.DruidPooledConnection.prepareStatement(DruidPooledConnection.java:339)

how can i  resolve it? please
