### ISSUE TITLE
It always throw ClassCastException with newer version of JDK

### ISSUE THREAD

**Issue by achimbab** [housepower/ClickHouse-Native-JDBC#87]
### Used Version
1.6-stable

### Stack Trace
```
java.lang.ClassCastException: class [B cannot be cast to class [C ([B and [C are in module java.base of loader 'bootstrap')

	at com.github.housepower.jdbc.misc.StringViewCoding.getValues(StringViewCoding.java:25)
	at com.github.housepower.jdbc.misc.SQLLexer.<init>(SQLLexer.java:11)
	at com.github.housepower.jdbc.stream.ValuesWithParametersInputFormat.<init>(ValuesWithParametersInputFormat.java:27)
	at com.github.housepower.jdbc.statement.ClickHousePreparedInsertStatement.executeBatch(ClickHousePreparedInsertStatement.java:61)
	at com.kakao.tiara.EnricherEntryConverterTest.insertLog2ClickHouse(EnricherEntryConverterTest.java:321)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
```

### TestCase
```
    System.setProperty("illegal-access", "allow");

    Class.forName("com.github.housepower.jdbc.ClickHouseDriver");
    Connection connection = DriverManager.getConnection("jdbc:clickhouse://127.0.0.1:9000");

    Statement stmt = connection.createStatement();

    PreparedStatement pstmt = connection.prepareStatement(insertQuery);
    pstmt.setString(1, "test");

    pstmt.addBatch();
    pstmt.executeBatch();
```

### Information
The problem seems to be in ClickHouse-native-JDBC. At least some versions use UNSAFE to get the 'value' field of String and then cast it to char[]. It was indeed a char[] in earlier JDK releases, but in recent JDK releases it's now a byte[]. That's why the cast fails. See 
https://bugs.openjdk.java.net/browse/JDK-8218540
```
    public static char[] getValues(String data) throws SQLException {
        try {
            Field field = getStringValueReflectField();
            return (char[]) field.get(data);
        } catch (IllegalAccessException e) {
            throw new SQLException("Cannot get java.lang.String values field", e);
        }
    }
```

**Comment by achimbab** [comment]
It is possible to use official Clickhouse JDBC for now.
ClickHouse-Native-JDBC also a good lib for ClickHouse, but there is officially support lib.

**Comment by sundy-li** [comment]
Really sorry for the delay, this bug is fixed in ac9391585ded977d803c61a04d0ee1c06443fdce.

**Comment by achimbab** [comment]
@sundy-li No worry, thank you :)

**Comment by sundy-li** [comment]
Closing this issue, feel free to re-open a closed issue if needed
