### ISSUE TITLE
[bug] isValid for connection - not correct

### ISSUE THREAD

**Issue by gapikru** [housepower/ClickHouse-Native-JDBC#91]
### JDBC version in pom.xml
1.6 or 1.7

### ClickHouse version
-

### Error  logs
17:35:39.555 [HikariPool-1 connection adder] ERROR jdbc.sqltiming - 5. Connection.isValid(1)
java.sql.SQLException: Read timed out
	at com.github.housepower.jdbc.connect.PhysicalConnection.receiveResponse(PhysicalConnection.java:88)
	at com.github.housepower.jdbc.connect.PhysicalConnection.receiveHello(PhysicalConnection.java:72)
	at com.github.housepower.jdbc.ClickHouseConnection.serverInfo(ClickHouseConnection.java:180)
	at com.github.housepower.jdbc.ClickHouseConnection.createPhysicalInfo(ClickHouseConnection.java:164)
	at com.github.housepower.jdbc.ClickHouseConnection.getHealthyPhysicalConnection(ClickHouseConnection.java:150)
	at com.github.housepower.jdbc.ClickHouseConnection.sendQueryRequest(ClickHouseConnection.java:119)
	at com.github.housepower.jdbc.statement.ClickHouseStatement.executeUpdate(ClickHouseStatement.java:46)
	at com.github.housepower.jdbc.statement.ClickHouseStatement.executeQuery(ClickHouseStatement.java:34)
	at com.github.housepower.jdbc.statement.ClickHouseStatement.execute(ClickHouseStatement.java:29)
	at com.github.housepower.jdbc.ClickHouseConnection.isValid(ClickHouseConnection.java:106)
	at net.sf.log4jdbc.ConnectionSpy.isValid(ConnectionSpy.java:548)
	at com.zaxxer.hikari.pool.PoolBase.checkValidationSupport(PoolBase.java:454)
	at com.zaxxer.hikari.pool.PoolBase.checkDriverSupport(PoolBase.java:433)
	at com.zaxxer.hikari.pool.PoolBase.setupConnection(PoolBase.java:402)
	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:355)
	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:201)
	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:473)
	at com.zaxxer.hikari.pool.HikariPool.access$100(HikariPool.java:71)
	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:727)
	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:713)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.net.SocketTimeoutException: Read timed out
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
	at java.net.SocketInputStream.read(SocketInputStream.java:171)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at com.github.housepower.jdbc.buffer.SocketBuffedReader.refill(SocketBuffedReader.java:66)
	at com.github.housepower.jdbc.buffer.SocketBuffedReader.readBinary(SocketBuffedReader.java:34)
	at com.github.housepower.jdbc.serializer.BinaryDeserializer.readVarInt(BinaryDeserializer.java:23)
	at com.github.housepower.jdbc.protocol.RequestOrResponse.readFrom(RequestOrResponse.java:32)
	at com.github.housepower.jdbc.connect.PhysicalConnection.receiveResponse(PhysicalConnection.java:86)
	... 23 common frames omitted

### Other descriptions

In Java Connection isValid(timeout) - timeout in second.
https://docs.oracle.com/javase/7/docs/api/java/sql/Connection.html#isValid(int)

In Java Socket setSoTimeout(timeout) - timeout in milliseonds
https://docs.oracle.com/javase/7/docs/api/java/net/Socket.html#setSoTimeout(int)

**ClickHouseConnection.java**
```
public boolean isValid(int timeout) throws SQLException {
        ClickHouseConfig validConfigure = configure.copy();
        validConfigure.setQueryTimeout(timeout);    // <- BUG  (timeout in seconds)
   
private static PhysicalInfo.ServerInfo serverInfo(PhysicalConnection physical, ClickHouseConfig configure) {
      HelloResponse response = physical.receiveHello(configure.queryTimeout(), null);  // <- (timeout in seconds)
```

**PhysicalConnection.java**
```
public RequestOrResponse receiveResponse(int soTimeout, PhysicalInfo.ServerInfo info) throws SQLException {
        try {
            socket.setSoTimeout(soTimeout);   // <- soTimeout - in seconds by need milliseconds
            return RequestOrResponse.readFrom(deserializer, info);
        } catch (IOException ex) {
            throw new SQLException(ex.getMessage(), ex);
        }
}
```

**Comment by sundy-li** [comment]
Thank you.

**Comment by gapikru** [comment]
Hello!

In my opinion, it is better fix this:
```
@@ -97,7 +97,7 @@ public class ClickHouseConnection extends SQLConnection {
     @Override
     public boolean isValid(int timeout) throws SQLException {
         ClickHouseConfig validConfigure = configure.copy();
-        validConfigure.setQueryTimeout(timeout);
+        validConfigure.setQueryTimeout(timeout*1000);
         Connection connection = null;
         Statement statement = null;
         try {
```

And do not correct  PhysicalConnection.java

Since isValid always takes seconds, and receiveResponse always takes milliseconds.

**Comment by sundy-li** [comment]
Right!
