### ISSUE TITLE
avg() causing exception

### ISSUE THREAD

**Issue by Sir-Will** [housepower/ClickHouse-Native-JDBC#95]
**JDBC version:** 1.7-stable
**ClickHouse version:** 19.4.1

Trying to execute the following query with the `avg()` functions causes the exception below. Executing the query directly inside the clickhouse client works without issues.

```sql
SELECT
    avg(X),
    avg(Y),
    avg(Z),
    EventName,
    WorldUuid,
    Target,
    Player,
    Cause,
    date,
    COUNT(*) AS total,
    toUInt64(toDateTime(date)) AS Created
FROM prism_sponge7_test_records
WHERE (Created >= 1565992623) AND ((WorldUuid = 'cda8cf62-f31e-46b4-a069-c21e45b06efb') AND (X > 197) AND (X < 207) AND                                                                                                                                                                                                      (Y > 59) AND (Y < 69) AND (Z > 204) AND (Z < 214))
GROUP BY
    EventName,
    WorldUuid,
    Target,
    Player,
    Cause,
    date
ORDER BY Created DESC

```

```
java.sql.SQLException
	at com.github.housepower.jdbc.misc.Validate.isTrue(Validate.java:14)
	at com.github.housepower.jdbc.misc.Validate.isTrue(Validate.java:8)
	at com.github.housepower.jdbc.data.Block.getPositionByName(Block.java:68)
	at com.github.housepower.jdbc.ClickHouseResultSet.findColumn(ClickHouseResultSet.java:235)
	at com.github.housepower.jdbc.ClickHouseResultSet.getInt(ClickHouseResultSet.java:43)
	at com.helion3.prism.storage.clickhouse.ClickhouseRecords.query(ClickhouseRecords.java:122)
	at com.helion3.prism.util.AsyncUtil.lambda$async$1(AsyncUtil.java:57)
	at org.spongepowered.api.scheduler.Task$Builder.lambda$execute$0(Task.java:139)
	at org.spongepowered.common.scheduler.SchedulerBase.lambda$startTask$0(SchedulerBase.java:192)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by Sir-Will** [comment]
Nvm, I'm blind.
