### ISSUE TITLE
Is it not supporting mybatis?

### ISSUE THREAD

**Issue by ifengkou** [housepower/ClickHouse-Native-JDBC#96]
### JDBC version in pom.xml
1.8

### ClickHouse version
19.11.2

### Error  logs
```
Caused by: java.sql.SQLFeatureNotSupportedException
	at com.github.housepower.jdbc.wrapper.SQLResultSet.getType(SQLResultSet.java:324)
	at com.zaxxer.hikari.pool.HikariProxyResultSet.getType(HikariProxyResultSet.java)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at ......................
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:426)
	... 38 more
```

### Other descriptions
```
<select id="getAll" resultType="cn.ifengkou.db.timeseries.model.TestModel">
        select * from test_jdbc_example
</select>
```

**Comment by gaoxiong523** [comment]
com.github.housepower.jdbc.wrapper.SQLConnection
直接抛错误了,所以现在是不支持的
```java
   @Override
    public DatabaseMetaData getMetaData() throws SQLException {
        throw new SQLFeatureNotSupportedException();
    }
```

**Comment by zhilinli123** [comment]
请问 最后是怎么解决的呢？

**Comment by gaoxiong523** [comment]
> 请问 最后是怎么解决的呢？

官方github 已经更新了啊 ，现在是可以用的，直接用mybatis 就可以了

**Comment by zhilinli123** [comment]
@gaoxiong523 我用的api 并不是mybatis 我不知道应如何配置它
